OAKHILL/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Organization</label>
        <type>Text</type>
    </fields>
</CustomObject>

OAKHILL/src/objects/Document_Recipient__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Document Recipients</relationshipLabel>
        <relationshipName>Document_Recipients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investor_Report_Document__c</fullName>
        <label>Investor Report Document</label>
        <referenceTo>Investor_Report_Document__c</referenceTo>
        <relationshipLabel>Document Recipients</relationshipLabel>
        <relationshipName>Document_Recipients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Unsent</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Document Recipient</label>
    <nameField>
        <displayFormat>D-{000000}</displayFormat>
        <label>Document  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OAKHILL/src/objects/Fund__c.object
<CustomObject>
    <fields>
        <fullName>Fund_Family__c</fullName>
        <label>Fund Family</label>
        <referenceTo>Fund_Family__c</referenceTo>
        <relationshipLabel>Fund</relationshipLabel>
        <relationshipName>Fund</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OAKHILL/src/objects/Fund_Family__c.object
<CustomObject>
    <label>Fund Family</label>
    <nameField>
        <label>Fund Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fund Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OAKHILL/src/objects/Investor_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Balance_Statement__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Balance Statement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Capital_Call__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Capital Call</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Investor Contacts</relationshipLabel>
        <relationshipName>Investor_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Estimate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Estimate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investment__c</fullName>
        <label>Investment</label>
        <referenceTo>Related_Account__c</referenceTo>
        <relationshipLabel>Investor Contacts</relationshipLabel>
        <relationshipName>Investor_Contacts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investor Contact</label>
    <nameField>
        <displayFormat>IC-{00000}</displayFormat>
        <label>Investor Contacts Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investor Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OAKHILL/src/objects/Investor_Report_Document__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Transaction_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <referenceTo>Related_Account__c</referenceTo>
        <relationshipName>Transaction_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Report_Generator__c</fullName>
        <label>Report Generator</label>
        <referenceTo>Report_Generator__c</referenceTo>
        <relationshipName>Transaction_Documents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Unsent</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipName>Transaction_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Investor Report Document</label>
    <nameField>
        <displayFormat>TD-{00000}</displayFormat>
        <label>Investor Report Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investor Report Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OAKHILL/src/objects/Legal_Entity__c.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Legal_Entities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tax_Number__c</fullName>
        <label>Tax Number</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Legal Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OAKHILL/src/objects/Related_Account__c.object
<CustomObject>
    <fields>
        <fullName>Fund__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fund</label>
        <referenceTo>Fund__c</referenceTo>
        <relationshipLabel>Related Accounts</relationshipLabel>
        <relationshipName>Related_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Entity__c</fullName>
        <label>Legal Entity</label>
        <referenceTo>Legal_Entity__c</referenceTo>
        <relationshipName>Investments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Related Account</label>
    <nameField>
        <label>Related Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OAKHILL/src/objects/Report_Generator__c.object
<CustomObject>
    <fields>
        <fullName>Fund__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fund</label>
        <referenceTo>Fund__c</referenceTo>
        <relationshipLabel>Report Generator</relationshipLabel>
        <relationshipName>Report_Generator</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Report_Generator_Type__c</fullName>
        <label>Report Generator Type</label>
        <picklist>
            <picklistValues>
                <fullName>Capital Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Call Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Run_Date__c</fullName>
        <label>Run Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Opened</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Report Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documents In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emailed except Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fully Emailed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Emailed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Report Generator</label>
    <nameField>
        <label>Report Generator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Report Generator</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OAKHILL/src/objects/SL_LoopParameterForEmail__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>DDPId__c</fullName>
        <label>DDPId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Delivery_Option_Id__c</fullName>
        <label>Delivery Option Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>SL_LoopParameterForEmail</label>
</CustomObject>

OAKHILL/src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Capital_Call__c</fullName>
        <label>Capital Call %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <label>Related Account</label>
        <referenceTo>Related_Account__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Report_Generator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Report Generator</label>
        <referenceTo>Report_Generator__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Distribution</fullName>
        <active>true</active>
        <label>Distribution</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OAKHILL/src/classes/SL_Test_WS_EmailDocument.cls
/**
* \arg ClassName      : SL_Test_WS_EmailDocument
* \arg JIRATicket     : OAKHILL-23
* \arg CreatedOn      : 30/DEC/2014
* \arg LastModifiedOn : 30/DEC/2014
* \arg CreatededBy    : Pankaj Ganwani
* \arg ModifiedBy     : Pankaj Ganwani
* \arg Description    : This class serves as test class for SL_WS_EmailDocument webservice.
*/
@isTest
private class SL_Test_WS_EmailDocument 
{
    static final String strCustomObjectRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName =:'Custom_Object'].Id;
    static final String strEmailRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName =:'Email'].Id;
    static Account objAccount;
    static Fund_Family__c objFundFamily;
    static Fund__c objFund;
    static Legal_Entity__c objLegalEntity;
    static List<Report_Generator__c> lstReportGenerator;
    static List<Related_Account__c> lstRelatedAccount;
    static List<Transaction__c> lstTransaction;
    static List<Contact> lstContact;
    static List<Investor_Contact__c> lstInvestorContact;
    static List<Investor_Report_Document__c> lstTransactionDocument;
    static List<Document_Recipient__c> lstDocumentRecipient;
    static List<Loop__DDP__c> lstDDP;
    static List<Loop__DDP_Integration_Option__c> lstDeliveryOption;
    static List<SL_LoopParameterForEmail__c> lstLoopParametersForEmail;
    static List<LStore__Stored_Document__c> lstStoredDocument;
    //create data
    private static void createData()
    {
    	objAccount = new Account(Name = 'Account1');
    	insert objAccount;
    	
    	lstContact = new List<Contact>{
    									 new Contact(LastName = 'Test Contact 1', AccountId = objAccount.Id),
    									 new Contact(LastName = 'Test Contact 2', AccountId = objAccount.Id),
    									 new Contact(LastName = 'Test Contact 3', AccountId = objAccount.Id),
    									 new Contact(LastName = 'Test Contact 4', AccountId = objAccount.Id)
    								  };
    	insert lstContact;
    	
    	lstDDP = new List<Loop__DDP__c>{
    										new Loop__DDP__c(Name = 'Capital Call', Loop__Object_Name__c = 'Investor_Report_Document__c', RecordTypeId = strCustomObjectRecordTypeId),
    										new Loop__DDP__c(Name = 'Capital Call Statement', Loop__Object_Name__c = 'Investor_Report_Document__c', RecordTypeId = strCustomObjectRecordTypeId),
    										new Loop__DDP__c(Name = 'Distribution', Loop__Object_Name__c = 'Investor_Report_Document__c', RecordTypeId = strCustomObjectRecordTypeId)
    								   };
    	insert lstDDP;
    	
    	lstDeliveryOption = new List<Loop__DDP_Integration_Option__c>{
    																	  new Loop__DDP_Integration_Option__c(Name = 'Send to Loop Storage', RecordTypeId = strEmailRecordTypeId, Loop__DDP__c = lstDDP[0].Id),
    																	  new Loop__DDP_Integration_Option__c(Name = 'Send to Loop Storage', RecordTypeId = strEmailRecordTypeId, Loop__DDP__c = lstDDP[1].Id),
    																	  new Loop__DDP_Integration_Option__c(Name = 'Send to Loop Storage', RecordTypeId = strEmailRecordTypeId, Loop__DDP__c = lstDDP[2].Id)
    																 };
   		insert lstDeliveryOption;
   		
   		objFundFamily = new Fund_Family__c(Name = 'Fund_Family_1');
		insert objFundFamily;
		
		objFund = new Fund__c(Name = 'Name', Fund_Family__c = objFundFamily.Id );
		insert objFund;
		
		lstReportGenerator = new List<Report_Generator__c>{
																new Report_Generator__c(Name = 'RG 1', Run_Date__c = date.today(), Report_Generator_Type__c = 'Capital Call', Fund__c = objFund.Id),
																new Report_Generator__c(Name = 'RG 2', Run_Date__c = date.today(), Report_Generator_Type__c = 'Capital Call Statement', Fund__c = objFund.Id),
																new Report_Generator__c(Name = 'RG 3', Run_Date__c = date.today(), Report_Generator_Type__c = 'Distribution', Fund__c = objFund.Id)
														  };
		insert lstReportGenerator;
		
		Legal_Entity__c objLegal_Entity = new Legal_Entity__c(Organization__c = objAccount.Id, 
																	Name = 'LegalEntity1', 
																	Tax_Number__c = '123450');
		insert objLegal_Entity;
		
		lstRelatedAccount = new List<Related_Account__c>{
															new  Related_Account__c(Name = 'RelatedAccount1', 
																					Legal_Entity__c = objLegal_Entity.Id, Fund__c = objFund.Id),
															new  Related_Account__c(Name = 'RelatedAccount2', 
																					Legal_Entity__c = objLegal_Entity.Id, Fund__c = objFund.Id),
															new  Related_Account__c(Name = 'RelatedAccount3', 
																					Legal_Entity__c = objLegal_Entity.Id, Fund__c = objFund.Id)
														};
		insert lstRelatedAccount;
		
		lstInvestorContact = new List<Investor_Contact__c>{
																new Investor_Contact__c(Contact__c = lstContact[0].Id, Investment__c = lstRelatedAccount[0].Id, Capital_Call__c = true, Estimate__c = true, Balance_Statement__c = true),
																new Investor_Contact__c(Contact__c = lstContact[1].Id, Investment__c = lstRelatedAccount[1].Id, Capital_Call__c = true, Estimate__c = true, Balance_Statement__c = true),
																new Investor_Contact__c(Contact__c = lstContact[2].Id, Investment__c = lstRelatedAccount[2].Id, Capital_Call__c = true, Estimate__c = true, Balance_Statement__c = true)
														  };
		insert lstInvestorContact;
		
		lstTransaction = new List<Transaction__c>{
													new Transaction__c(Name = 'Test TR 1', Related_Account__c = lstRelatedAccount[0].Id, Date__c = date.today()),
													new Transaction__c(Name = 'Test TR 2', Related_Account__c = lstRelatedAccount[1].Id, Date__c = date.today()),
													new Transaction__c(Name = 'Test TR 3', Related_Account__c = lstRelatedAccount[2].Id, Date__c = date.today())
												 };
		insert lstTransaction;
		
		lstTransactionDocument = new List<Investor_Report_Document__c>{
																		new Investor_Report_Document__c(Report_Generator__c = lstReportGenerator[0].Id, Related_Account__c = lstRelatedAccount[0].Id, Status__c = 'Approved'),
																		new Investor_Report_Document__c(Report_Generator__c = lstReportGenerator[0].Id, Related_Account__c = lstRelatedAccount[1].Id, Status__c = 'Approved'),
																		new Investor_Report_Document__c(Report_Generator__c = lstReportGenerator[0].Id, Related_Account__c = lstRelatedAccount[2].Id, Status__c = 'Approved')
																  };
		
		insert lstTransactionDocument;
		
		lstDocumentRecipient = new List<Document_Recipient__c>{
																	new Document_Recipient__c(Investor_Report_Document__c = lstTransactionDocument[0].Id, Contact__c = lstContact[0].Id),
																	new Document_Recipient__c(Investor_Report_Document__c = lstTransactionDocument[0].Id, Contact__c = lstContact[0].Id),
																	new Document_Recipient__c(Investor_Report_Document__c = lstTransactionDocument[1].Id, Contact__c = lstContact[1].Id),
																	new Document_Recipient__c(Investor_Report_Document__c = lstTransactionDocument[1].Id, Contact__c = lstContact[1].Id),
																	new Document_Recipient__c(Investor_Report_Document__c = lstTransactionDocument[2].Id, Contact__c = lstContact[2].Id),
																	new Document_Recipient__c(Investor_Report_Document__c = lstTransactionDocument[2].Id, Contact__c = lstContact[2].Id)
															  };
		insert lstDocumentRecipient;
		
		lstLoopParametersForEmail = new List<SL_LoopParameterForEmail__c>{
																			new SL_LoopParameterForEmail__c(Name = 'Capital Call', DDPId__c = lstDDP[0].Id, Delivery_Option_Id__c = lstDeliveryOption[0].Id),																	
																			new SL_LoopParameterForEmail__c(Name = 'Capital Call Statement', DDPId__c = lstDDP[1].Id, Delivery_Option_Id__c = lstDeliveryOption[1].Id),																	
																			new SL_LoopParameterForEmail__c(Name = 'Distribution', DDPId__c = lstDDP[2].Id, Delivery_Option_Id__c = lstDeliveryOption[2].Id)
														  		   		  };
		insert lstLoopParametersForEmail;
		
		lstStoredDocument = new List<LStore__Stored_Document__c>{
																	new LStore__Stored_Document__c(Name = 'Test Document 1', LStore__Related_Object_Id__c = lstTransactionDocument[0].Id),
																	new LStore__Stored_Document__c(Name = 'Test Document 2', LStore__Related_Object_Id__c = lstTransactionDocument[1].Id),
																	new LStore__Stored_Document__c(Name = 'Test Document 3', LStore__Related_Object_Id__c = lstTransactionDocument[2].Id)
																};
																
		insert lstStoredDocument;
    }
    
    //updating transaction document records
    private static void updateTransactionDocument()
    {
    	update new List<Investor_Report_Document__c>{
        											new Investor_Report_Document__c(Id = lstTransactionDocument[0].Id, Status__c = 'Approved'),
													new Investor_Report_Document__c(Id = lstTransactionDocument[1].Id, Status__c = 'Approved'),
													new Investor_Report_Document__c(Id = lstTransactionDocument[2].Id, Status__c = 'Approved')
        										};
    }
    
    static testMethod void checkForCapitalCall()
    {
    	createData();
        updateTransactionDocument();
        
        Test.startTest();
        SL_WS_EmailDocument.emailDocuments(lstReportGenerator[0].Id,'Capital Call');
        Test.stopTest();
    }
    
    static testMethod void checkForNull()
    {
    	createData();
     	updateTransactionDocument();
     	
        Test.startTest();
        SL_WS_EmailDocument.emailDocuments(lstReportGenerator[0].Id,NULL);
        Test.stopTest();
    }
    
    static testMethod void checkForDistribution()
    {
    	createData();
        updateTransactionDocument();
        
        Test.startTest();
        SL_WS_EmailDocument.emailDocuments(lstReportGenerator[0].Id,'Distribution');
        Test.stopTest();
    }
    
    static testMethod void checkForCapitalCallStatement()
    {
    	createData();
        updateTransactionDocument();
        
        Test.startTest();
        SL_WS_EmailDocument.emailDocuments(lstReportGenerator[0].Id,'Capital Call Statement');
        Test.stopTest();
    }    
}