OAKHILL/src/objects/Legal_Entity__c.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Legal_Entities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tax_Number__c</fullName>
        <label>Tax Number</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Legal Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OAKHILL/src/objects/Month_End_Balance__c.object
<CustomObject>
    <fields>
        <fullName>Commitment_Funded__c</fullName>
        <label>% Commitment Funded</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Commitment_Funded_c__c</fullName>
        <label>Commitment Funded</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_End_Balance__c</fullName>
        <label>Month-End Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Net_Balance__c</fullName>
        <label>Begin Balance Net</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <label>Related Account</label>
        <referenceTo>Related_Account__c</referenceTo>
        <relationshipLabel>Month End Balances</relationshipLabel>
        <relationshipName>Month_End_Balances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Month End Balance</label>
    <nameField>
        <label>Month End Balance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Month End Balances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OAKHILL/src/objects/Related_Account__c.object
<CustomObject>
    <fields>
        <fullName>Commitment_Funded__c</fullName>
        <label>Commitment Funded</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_NAV__c</fullName>
        <label>Current NAV</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Legal_Entity__c</fullName>
        <label>Legal Entity</label>
        <referenceTo>Legal_Entity__c</referenceTo>
        <relationshipName>Investments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Related Account</label>
    <nameField>
        <label>Related Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OAKHILL/src/classes/SL_Test_BatchUpdateRelatedAccount.cls
/**  
* \arg ClassName      : SL_Test_BatchUpdateRelatedAccount
* \arg JIRATicket     : OAKHILL-15
* \arg CreatedOn      : 24/OCT/2014
* \arg LastModifiedOn : 24/OCT/2014
* \arg CreatededBy    : Pankaj Ganwani
* \arg ModifiedBy     : -
* \arg Description    : This class serves as test class for SL_Batch_UpdateRelatedAccount to check its functionality
*/
@isTest
private class SL_Test_BatchUpdateRelatedAccount 
{
    static Legal_Entity__c objLegalEntity;
    static Related_Account__c objRelatedAccount;
    static Account objAccount;
    static List<Month_End_Balance__c> lstMonthEndBalance;
    
    //function to create data for testing functionality
    static void createData()
    {
    	objAccount = new Account(Name = 'Test Account');
    	insert objAccount;
    	
    	objLegalEntity = new Legal_Entity__c(Organization__c = objAccount.Id, Tax_Number__c = '1111');
    	insert objLegalEntity;
    	
    	objRelatedAccount = new Related_Account__c(Legal_Entity__c = objLegalEntity.Id);
    	insert objRelatedAccount;
    	
    	
    	
    	lstMonthEndBalance = new List<Month_End_Balance__c>{
    															new Month_End_Balance__c(Name = '20141010', Related_Account__c = objRelatedAccount.Id, Commitment_Funded_c__c = 123, Net_Balance__c = 8977),
    															new Month_End_Balance__c(Name = '20141011', Related_Account__c = objRelatedAccount.Id, Commitment_Funded_c__c = 124, Net_Balance__c = 8978),
    															new Month_End_Balance__c(Name = '20141012', Related_Account__c = objRelatedAccount.Id, Commitment_Funded_c__c = 125, Net_Balance__c = 8979),
    															new Month_End_Balance__c(Name = '20141013', Related_Account__c = objRelatedAccount.Id, Commitment_Funded_c__c = 126, Net_Balance__c = 8970)
    														};
    	insert lstMonthEndBalance;
    }
    
    //function to check the functionality of related account record update
    static testMethod void checkForRecordUpdate()
    {
    	createData();
    	
    	Test.startTest();
    	Database.executeBatch(new SL_Batch_UpdateRelatedAccount(),200);
    	Test.stopTest();
    	
    	System.assertEquals([SELECT Current_NAV__c FROM Related_Account__c WHERE Id =:objRelatedAccount.Id].Current_NAV__c, 8970);
    	System.assertEquals([SELECT Commitment_Funded__c FROM Related_Account__c WHERE Id =:objRelatedAccount.Id].Commitment_Funded__c, 126);
    }
}