OAKHILL/src/objects/MN_Joiner__c.object
<CustomObject>
    <fields>
        <fullName>MN_Page_Layout__c</fullName>
        <label>MN Page Layout</label>
        <referenceTo>MN_Page_Layout__c</referenceTo>
        <relationshipLabel>MN Joiners</relationshipLabel>
        <relationshipName>MN_Joiners</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MN_Related_List__c</fullName>
        <label>MN Related List</label>
        <referenceTo>MN_Related_List__c</referenceTo>
        <relationshipLabel>MN Joiners</relationshipLabel>
        <relationshipName>MN_Joiners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>MN Joiner</label>
    <nameField>
        <label>MN Joiner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MN Joiners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

OAKHILL/src/objects/MN_Page_Layout__c.object
<CustomObject>
    <fields>
        <fullName>Email_Prefill__c</fullName>
        <label>Email Prefill</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldSetName__c</fullName>
        <label>FieldSetName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile__c</fullName>
        <label>Profile</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MN Page Layout</label>
    <nameField>
        <label>MN Page Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MN Page Layouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OAKHILL/src/objects/MN_Related_List__c.object
<CustomObject>
    <fields>
        <fullName>DisplayName__c</fullName>
        <label>DisplayName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FieldSetName__c</fullName>
        <label>FieldSetName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <label>ObjectName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>MN Related List</label>
    <nameField>
        <label>MN Related List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MN Related Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

OAKHILL/src/classes/SL_TestMNJoinerHandler.cls
@isTest
public class SL_TestMNJoinerHandler {

	static testMethod void unitTestCode() {

		MN_Page_Layout__c objLayout = new MN_Page_Layout__c(Name = 'Master_Task',  FieldSetName__c = 'SL_TaskDescription', 
															Email_Prefill__c = '', Profile__c = 'System Administrator');
		insert objLayout;

		MN_Related_List__c objRelatedList = new MN_Related_List__c(Name = 'Companies Discussed', DisplayName__c = 'DisplayName__c',
																   FieldSetName__c = 'SL_CompaniesDiscussedFieldSet', ObjectName__c = 'Account', Order__c = 1);

		insert objRelatedList;

		insert new MN_Joiner__c(MN_Page_Layout__c = objLayout.Id, MN_Related_List__c = objRelatedList.Id);

		try {

			insert new MN_Joiner__c(MN_Page_Layout__c = objLayout.Id, MN_Related_List__c = objRelatedList.Id);

		} catch(Exception e) {

			system.assert(true, e.getMessage().contains('Record already exists with provided MN Related List and MN Page Layout combination, Please provide different values'));
		}
	}
}