HIL/src/objects/Financial_Account__c.object
<CustomObject>
    <description>Custom object to track financial account records populated via nightly integration with data warehouse.</description>
    <fields>
        <fullName>Money_Market_Balance__c</fullName>
        <label>Money Market Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Account_Equity__c</fullName>
        <label>Total Account Equity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL/src/objects/Group_Member__c.object
<CustomObject>
    <description>Custom object that acts as a junction between a Client &amp; Prospect record and a Relationship Group record.</description>
    <fields>
        <fullName>Client_Prospect__c</fullName>
        <label>Client/Prospect</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Relationship_Group__c</fullName>
        <label>Relationship Group</label>
        <referenceTo>Relationship_Group__c</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Primary_Asset_RU__c</fullName>
        <description>Field needed for Rollup</description>
        <label>Total Primary Asset RU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>GM-{00000}</displayFormat>
        <label>Group Member #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HIL/src/objects/Hilliard_Lyons_Account__c.object
<CustomObject>
    <description>Custom object to track the many to many relationship that exists between a Financial Account record and a Client &amp; Prospect record.</description>
    <fields>
        <fullName>Asset_Value_RU__c</fullName>
        <description>Field needed for Rollup</description>
        <label>Asset Value RU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Hilliard Lyons Accounts</relationshipLabel>
        <relationshipName>Financial_Account_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Hilliard Lyons Accounts</relationshipLabel>
        <relationshipName>Financial_Account_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Hilliard Lyons Account</label>
    <nameField>
        <displayFormat>HLA-{00000}</displayFormat>
        <label>Hilliard Lyons Account#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hilliard Lyons Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HIL/src/objects/Relationship_Group__c.object
<CustomObject>
    <description>Custom object to track a combination of Client &amp; Prospect records related via many to many relationship with the Group Member junction object.</description>
    <label>Relationship Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL FullSandbox/src/classes/SL_Test_FinancialAccountHandler.cls
/**
* \arg ClassName      : SL_Test_FinancialAccountHandler
* \arg JIRATicket     : HIL-7
* \arg CreatedOn      : 18/FEB/2015
* \arg LastModifiedOn : -
* \arg CreatededBy    : Pankaj Ganwani
* \arg ModifiedBy     : -
* \arg Description    : This class serves as test class for SL_FinancialAccount trigger handler and is used to check the functionality for updation of HL account records corresponding to updated financial accounts which in turn updates the Group member records.
*/
@isTest
private class SL_Test_FinancialAccountHandler 
{
    static final String strPersonRecordType = [SELECT Id FROM RecordType WHERE SobjectType=:'Account' AND IsPersonType = true LIMIT 1].Id;
    
    static List<Financial_Account__c> lstFA;
    static List<Hilliard_Lyons_Account__c> lstHLAccount;
    static List<Account> lstAccount;
    static List<Group_Member__c> lstGM;
    static List<Relationship_Group__c> lstRG;
    
    //function to prepare test data
    private static void createData()
    {
    	lstRG = new List<Relationship_Group__c>{
    												new Relationship_Group__c(Name = 'Test RG 1'),
    												new Relationship_Group__c(Name = 'Test RG 2')
    										   };
    	insert lstRG;
    	
    	lstAccount = new List<Account>{
    										new Account(FirstName = 'Test', LastName = 'Account 1', RecordTypeId = strPersonRecordType),
    										new Account(FirstName = 'Test', LastName = 'Account 2', RecordTypeId = strPersonRecordType)
    								  };
    	insert lstAccount;
    	
    	lstGM = new List<Group_Member__c>{
    										new Group_Member__c(Client_Prospect__c = lstAccount[0].Id, Relationship_Group__c = lstRG[0].Id),
    										new Group_Member__c(Client_Prospect__c = lstAccount[0].Id, Relationship_Group__c = lstRG[1].Id),
    										new Group_Member__c(Client_Prospect__c = lstAccount[1].Id, Relationship_Group__c = lstRG[0].Id),
    										new Group_Member__c(Client_Prospect__c = lstAccount[1].Id, Relationship_Group__c = lstRG[1].Id)
    									 };
    	insert lstGM;
    	
    	lstFA = new List<Financial_Account__c>{
    												new Financial_Account__c(Name = 'Test FA 1', Money_Market_Balance__c = 123, Revenue__c = 900, Total_Account_Equity__c = 981),
    												new Financial_Account__c(Name = 'Test FA 1', Money_Market_Balance__c = 123, Revenue__c = 900, Total_Account_Equity__c = 901)
    										  };
    	insert lstFA;
    	
    	lstHLAccount = new List<Hilliard_Lyons_Account__c>{
    															new Hilliard_Lyons_Account__c(Financial_Account__c	 = lstFA[0].Id, Client__c = lstAccount[0].Id, Role__c = 'Primary'),
    															new Hilliard_Lyons_Account__c(Financial_Account__c	 = lstFA[0].Id, Client__c = lstAccount[1].Id, Role__c = 'Primary'),
    															new Hilliard_Lyons_Account__c(Financial_Account__c	 = lstFA[1].Id, Client__c = lstAccount[0].Id, Role__c = 'Primary'),
    															new Hilliard_Lyons_Account__c(Financial_Account__c	 = lstFA[1].Id, Client__c = lstAccount[1].Id, Role__c = 'Primary')
    													  };
    	insert lstHLAccount;
    }
    
    //function to check the functionality of update
    static testMethod void checkForUpdate() 
    {
        createData();
        
        lstFA[0].Money_Market_Balance__c = 222;
        
        Test.startTest();
        update lstFA[0];
        Test.stopTest();
        
        //System.assertEquals([SELECT Asset_Value_RU__c FROM Hilliard_Lyons_Account__c WHERE Id =: lstHLAccount[0].Id].Asset_Value_RU__c, 981);
        //System.assertEquals([SELECT Total_Primary_Asset_RU__c FROM Group_Member__c WHERE Id =: lstGM[0].Id].Total_Primary_Asset_RU__c, 1882);
    }
    
    //function to check the functionality of delete
    static testMethod void checkForDelete()
    {
    	createData();
    	delete lstFA[0];
    }
}