HIL/src/objects/Financial_Account__c.object
<CustomObject>
    <description>Custom object to track financial account records populated via nightly integration with data warehouse.</description>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep Code</label>
        <referenceTo>Rep_Code__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL/src/objects/Group_Member__c.object
<CustomObject>
    <description>Custom object that acts as a junction between a Client &amp; Prospect record and a Relationship Group record.</description>
    <fields>
        <fullName>Client_Prospect__c</fullName>
        <label>Client/Prospect</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Relationship_Group__c</fullName>
        <label>Relationship Group</label>
        <referenceTo>Relationship_Group__c</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>GM-{00000}</displayFormat>
        <label>Group Member #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HIL/src/objects/Hilliard_Lyons_Account__c.object
<CustomObject>
    <description>Custom object to track the many to many relationship that exists between a Financial Account record and a Client &amp; Prospect record.</description>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Hilliard Lyons Accounts</relationshipLabel>
        <relationshipName>Financial_Account_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Hilliard Lyons Accounts</relationshipLabel>
        <relationshipName>Financial_Account_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <formula>Financial_Account__r.Rep_Code__r.Name</formula>
        <label>Rep Code</label>
        <type>Text</type>
    </fields>
    <label>Hilliard Lyons Account</label>
    <nameField>
        <displayFormat>HLA-{00000}</displayFormat>
        <label>Hilliard Lyons Account#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hilliard Lyons Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HIL/src/objects/Relationship_Group__c.object
<CustomObject>
    <description>Custom object to track a combination of Client &amp; Prospect records related via many to many relationship with the Group Member junction object.</description>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep Code</label>
        <referenceTo>Rep_Code__c</referenceTo>
        <relationshipLabel>Relationship Groups</relationshipLabel>
        <relationshipName>Relationship_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL/src/objects/Rep_Code__c.object
<CustomObject>
    <description>Custom object to track all Rep Codes.</description>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <externalId>true</externalId>
        <label>Rep Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Rep Code</label>
    <nameField>
        <label>Rep Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rep Codes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL/src/objects/Rep_Code_User__c.object
<CustomObject>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep Code</label>
        <referenceTo>Rep_Code__c</referenceTo>
        <relationshipLabel>Rep Code Users</relationshipLabel>
        <relationshipName>Rep_Code_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Rep_Code_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rep Code User</label>
    <nameField>
        <label>Rep Code User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rep Code Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HIL FullSandbox/src/classes/SL_Test_Batch_ConvertActivities.cls
@isTest
private class SL_Test_Batch_ConvertActivities {
	
	@isTest static void test_method_one()
	{
		Account a = new Account();
		a.Name = 'test account';

		insert a;

		Rep_Code__c rc = new Rep_Code__c();
		rc.Rep_Code__c = 'PA01';

		insert rc;

		Rep_Code__c rc2 = new Rep_Code__c();
		rc2.Rep_Code__c = 'PA02';

		insert rc2;

		Rep_Code_User__c rcu = new Rep_Code_User__c();
		rcu.Rep_Code__c = rc.Id;
		rcu.User__c = UserInfo.getUserId();

		insert rcu;

		User u = [Select Id
				  From User
				  WHERE Profile.Name != 'System Administrator' AND IsActive = true LIMIT 1];

		Rep_Code_User__c rcu2 = new Rep_Code_User__c();
		rcu2.Rep_Code__c = rc2.Id;
		rcu2.User__c = u.Id;

		insert rcu2;

		Relationship_Group__c r = new Relationship_Group__c();
		r.Name = 'Test group';
		r.Rep_Code__c = rc2.Id;

		insert r;

		Group_Member__c gm = new Group_Member__c();
		gm.Client_Prospect__c = a.Id;
		gm.Relationship_Group__c = r.Id;

		insert gm;

		Financial_Account__c fa = new Financial_Account__c();
		fa.Rep_Code__c = rc.Id;

		insert fa;

		Hilliard_Lyons_Account__c hla = new Hilliard_Lyons_Account__c();
		hla.Financial_Account__c = fa.Id;
		hla.Client__c = a.Id;

		insert hla;

		Task t = new Task();
		t.WhatId = r.Id;

		insert t;

		Attachment att = new Attachment();
		att.Name = 'Test';
		att.Body = Blob.valueOf('test');
		att.ParentId = t.Id;
		insert att;

		Test.startTest();
		SL_Batch_ConvertActivities cjBatch = new SL_Batch_ConvertActivities();
		Database.executeBatch(cjBatch);
		Test.stopTest();
	}
	
}