HIL/src/objects/Financial_Plan__c.object
<CustomObject>
    <description>Custom object to track data related to a financial plan and related data.</description>
    <fields>
        <fullName>Client_Prospect__c</fullName>
        <label>Client/Prospect</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Plans</relationshipLabel>
        <relationshipName>Financial_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Relationship_Group__c</referenceTo>
        <relationshipLabel>Financial Plans</relationshipLabel>
        <relationshipName>Financial_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Plan</label>
    <nameField>
        <label>Financial Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HIL/src/objects/Relationship_Group__c.object
<CustomObject>
    <description>Custom object to track a combination of Client &amp; Prospect records related via many to many relationship with the Group Member junction object.</description>
    <label>Relationship Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL FullSandbox/src/classes/SL_FinancialPlanHandler.cls
/**
* @TriggerName  : SL_FinancialPlanHandler   
* @JIRATicket   : HIL-21
* @CreatedOn    : 13/OCT/2015
* @CreatedBy    : Pankaj Ganwani
* @Description  : Trigger to update HouseHold field value on inserted Financial_Plan__c.
*/
public with sharing class SL_FinancialPlanHandler 
{
	/* Start - Constructor */
    public SL_FinancialPlanHandler()
    {
        //Do Nothing
    }
    /* End - Constructor */
    
    public static void onBeforeInsert(List <Financial_Plan__c> lstFP)
    {
        updateHousehold(lstFP);
    }
    
    public static void onAfterInsert(List <Financial_Plan__c> lstFP)
    {
        createSharingRule(lstFP, true);
    }
    
    private static void updateHousehold(List<Financial_Plan__c> lstFP)
    {
    	Map<Id, Id> mapAccIdToHousehold = new Map<Id, Id>();
        Set<Id> setAccountIds = new Set<Id>();
        
        for(Financial_Plan__c objFP : lstFP)
        {
    		if(objFP.Client_Prospect__c!=NULL)
    			setAccountIds.add(objFP.Client_Prospect__c);
        }
        
        if(setAccountIds.isEmpty())
        	return;        
        mapAccIdToHousehold = SL_Util_CreateChildSharings.formAccountToHouseholdMapping(setAccountIds);
        
        for(Financial_Plan__c objFP : lstFP)
        {
        	if(mapAccIdToHousehold.containskey(objFP.Client_Prospect__c))
        		objFP.Relationship_Group__c = mapAccIdToHousehold.get(objFP.Client_Prospect__c);
        }
    }
    
    public static void createSharingRule(List <Financial_Plan__c> lstFP, Boolean isFPTrigger)
    {
        Map<Id,Id> mapFPIdToHouseHoldId = new Map<Id,Id>();
        
        for(Financial_Plan__c objFP : lstFP)
        {
        	if(objFP.Relationship_Group__c!=NULL) 
        		mapFPIdToHouseHoldId.put(objFP.Id, objFP.Relationship_Group__c);
        }
        
        if(!isFPTrigger)
        	Database.delete([SELECT Id FROM Financial_Plan__Share WHERE ParentId IN : mapFPIdToHouseHoldId.keyset()],false);
        
        Database.insert(SL_Util_CreateChildSharings.createSharingRecords(mapFPIdToHouseHoldId),false);
    }
}