HIL/src/objects/Group_Member__c.object
<CustomObject>
    <description>Custom object that acts as a junction between a Client &amp; Prospect record and a Relationship Group record.</description>
    <fields>
        <fullName>Client_Prospect__c</fullName>
        <label>Client/Prospect</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Contact_Date__c</fullName>
        <label>Last Contact Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Meeting_Date__c</fullName>
        <label>Last Meeting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Relationship_Group__c</fullName>
        <label>Relationship Group</label>
        <referenceTo>Relationship_Group__c</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grandchild</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grandparent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Husband</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trustee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wife</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>GM-{00000}</displayFormat>
        <label>Group Member #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HIL/src/objects/Note__c.object
<CustomObject>
    <fields>
        <fullName>Account_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>SLANotes_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ActivityDate__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Due Date Only</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Count_Towards_SLA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Count Towards SLA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Create_Joiner_Records__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Joiner Records</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Relationship_Group__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep Code</label>
        <referenceTo>Rep_Code__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on someone else</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Note</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Do</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Note</label>
    <nameField>
        <displayFormat>Note-{YY}-{00000000}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL/src/objects/Note_Joiner__c.object
<CustomObject>
    <fields>
        <fullName>Client_Prospect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client &amp; Prospect</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Member</label>
        <referenceTo>Group_Member__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Note</label>
        <referenceTo>Note__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Relationship_Group__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>TEXT(Note__r.Type__c)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Note Joiner</label>
    <nameField>
        <displayFormat>N-{000000}</displayFormat>
        <label>Note Joiner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Note Joiners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HIL/src/objects/Relationship_Group__c.object
<CustomObject>
    <description>Custom object to track a combination of Client &amp; Prospect records related via many to many relationship with the Group Member junction object.</description>
    <fields>
        <fullName>Last_Contact_Date__c</fullName>
        <label>Last Contact Date</label>
        <summarizedField>Group_Member__c.Last_Contact_Date__c</summarizedField>
        <summaryForeignKey>Group_Member__c.Relationship_Group__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Last_Meeting_Date__c</fullName>
        <label>Last Meeting Date</label>
        <summarizedField>Group_Member__c.Last_Meeting_Date__c</summarizedField>
        <summaryForeignKey>Group_Member__c.Relationship_Group__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep Code</label>
        <referenceTo>Rep_Code__c</referenceTo>
        <relationshipLabel>Relationship Groups</relationshipLabel>
        <relationshipName>Relationship_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holding Company</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Relationship Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL/src/objects/Rep_Code__c.object
<CustomObject>
    <description>Custom object to track all Rep Codes.</description>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <externalId>true</externalId>
        <label>Rep Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Rep Code</label>
    <nameField>
        <label>Rep Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rep Codes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL/src/objects/Rep_Code_User__c.object
<CustomObject>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep Code</label>
        <referenceTo>Rep_Code__c</referenceTo>
        <relationshipLabel>Rep Code Users</relationshipLabel>
        <relationshipName>Rep_Code_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Rep_Code_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rep Code User</label>
    <nameField>
        <label>Rep Code User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rep Code Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HIL/src/classes/SL_Note_Joiner_Handler.cls
public class SL_Note_Joiner_Handler
{
     /* start - global variables*/
    private boolean m_isExecuting = false;
    private integer BatchSize = 0;
    public Set<Note_Joiner__c> setNJ;
    public map<Id,Set<Id>> noteRCMap;
    /* end - global variables*/

    //Constructor of a Handler Class
    public SL_Note_Joiner_Handler(boolean isExecuting, integer size)
    {
        m_isExecuting = isExecuting;
        BatchSize = size;

        setNJ = new Set<Note_Joiner__c>();
        noteRCMap = new map<Id,Set<Id>>();
    }

    // This function will be called on OnAfterInsert of Task record.
    public void onAfterInsert(Map<Id, Note_Joiner__c> newMap)
    {
        //Updating Activities
        //updateTasks(mapNewTask, null);
        updateSLA(null,newMap);
    }
    
    // This function will be called on onAfterUpdate of Task record.
    public void onAfterUpdate(Map<Id, Note_Joiner__c> oldMap, Map<Id, Note_Joiner__c> newMap)
    {
        //Updating Activities
        //updateTasks(mapNewTask, mapOldTask);
        updateSLA(oldMap,newMap);
    }
    
    // This function will be called on onAfterUndelete of Task record.
    public void onAfterUndelete(Map<Id, Note_Joiner__c> newMap)
    {
        //Updating Activities
        //updateTasks(mapNewTask, null);
    }

    public void createJoinerRecs(map<Id,Note__c> newMap)
    {
        Set<Id> nIds = new Set<Id>();
        Set<Id> ownerIds = new Set<Id>();
        Note__c[] nList = new Note__c[]{};
        Note_Joiner__c[] njList = new Note_Joiner__c[]{};

        map<Id,Set<Id>> noteRelGrpMap = new map<Id,Set<Id>>();
        map<Id,Set<Id>> noteAcctMap = new map<Id,Set<Id>>();

        for(Note__c n : newMap.values())
        {
            if(n.Create_Joiner_Records__c)
            {
                nIds.add(n.Id);
            }
        }

        if(nIds != null && !nIds.isEmpty())
        {
            nList = [Select Id,OwnerId,
                            Account_del__c,
                            Relationship_Group__c,
                            Rep_Code__c
                     From Note__c
                     WHERE Id IN: nIds];

            for(Note__c n : nList)
            {
                if(n.Relationship_Group__c != null)
                {
                    if(noteRelGrpMap.containsKey(n.Relationship_Group__c))
                    {
                        noteRelGrpMap.get(n.Relationship_Group__c).add(n.Id);
                    }else
                    {
                        noteRelGrpMap.put(n.Relationship_Group__c,new Set<Id>{n.Id});
                    }
                }

                if(n.Account_del__c != null)
                {
                    if(noteAcctMap.containsKey(n.Account_del__c))
                    {
                        noteAcctMap.get(n.Account_del__c).add(n.Id);
                    }else
                    {
                        noteAcctMap.put(n.Account_del__c,new Set<Id>{n.Id});
                    }

                    ownerIds.add(n.OwnerId);
                }
            }

            populateGroupMembers(noteRelGrpMap);
            populateRelatedGroups(noteAcctMap,ownerIds);

            njList.addAll(setNJ);

            insert njList;
        }
    }

    public void populateGroupMembers(map<Id,Set<Id>> noteRelGrpMap)
    {
        Set<Note_Joiner__c> njSet = new Set<Note_Joiner__c>();
    
        List<Group_Member__c> groupMembers = [Select Client_Prospect__c,
                                                     Relationship_Group__c,
                                                     Relationship_Group__r.Rep_Code__c
                                              From Group_Member__c
                                              Where Relationship_Group__c IN: noteRelGrpMap.keyset()];
        
        for(Group_Member__c gm : groupMembers)
        {

            Set<Id> iTemp = noteRelGrpMap.get(gm.Relationship_Group__c);

            for(Id i : iTemp)
            {
                Note_Joiner__c nj = new Note_Joiner__c();

                nj.Client_Prospect__c = gm.Client_Prospect__c;
                nj.Note__c = i;

                njSet.add(nj);

                if(noteRCMap.containsKey(i))
                {
                    noteRCMap.get(i).add(gm.Relationship_Group__r.Rep_Code__c);
                }else
                {
                    noteRCMap.put(i, new Set<Id>{gm.Relationship_Group__r.Rep_Code__c});
                }
            }
        }

        setNJ.addAll(njSet);
    }

    public void populateRelatedGroups(map<Id,Set<Id>> noteAcctMap, Set<Id> ownerIds)
    {
        Set<Note_Joiner__c> njSet = new Set<Note_Joiner__c>();

        List<Rep_Code_User__c> rcuList = [select Rep_Code__c from Rep_Code_User__c where User__c IN: ownerIds];
        Set<Id> rcIds = new Set<Id>();
        
        for(Rep_Code_User__c r : rcuList)
        {
            rcIds.add(r.Rep_Code__c);
        }
              
        List<Group_Member__c> groupMembers = [select Client_Prospect__c,
                                                     Relationship_Group__c,
                                                     Relationship_Group__r.Rep_Code__c
                                              From Group_Member__c
                                              where Client_Prospect__c IN: noteAcctMap.keyset() AND Relationship_Group__r.Rep_Code__c IN: rcIds];
        
        for(Group_Member__c gm : groupMembers)
        {

            Set<Id> iTemp = noteAcctMap.get(gm.Client_Prospect__c);

            for(Id i : iTemp)
            {
                Note_Joiner__c nj = new Note_Joiner__c();

                nj.Client_Prospect__c = gm.Relationship_Group__c;
                nj.Note__c = i;

                njSet.add(nj);

                if(noteRCMap.containsKey(i))
                {
                    noteRCMap.get(i).add(gm.Relationship_Group__r.Rep_Code__c);
                }else
                {
                    noteRCMap.put(i, new Set<Id>{gm.Relationship_Group__r.Rep_Code__c});
                }
            }
        }

        setNJ.addAll(njSet);
    }
    
    public void updateSLA(Map<Id, Note_Joiner__c> oldMap, Map<Id, Note_Joiner__c> newMap)
    {
        Set<Id> noteIds = new Set<Id>();
        Set<Id> acctIds = new Set<Id>();
        Group_Member__c[] updGms = new Group_Member__c[]{};
        Set<Group_Member__c> setGms = new Set<Group_Member__c>();
        Set<Account> setAccts = new Set<Account>();
        Account[] updAccts = new Account[]{};
        map<Id,Group_Member__c[]> acctGmMap = new map<Id,Group_Member__c[]>();
        
        for(Note_Joiner__c n : newMap.values())
        {
            if(n.Note__c != null)
            {
                noteIds.add(n.Note__c);
			}
            
            if(n.Client_Prospect__c != null)
            {
                acctIds.add(n.Client_Prospect__c);
            }
        }
        
        map<Id,Account> acctMap = new map<Id,Account>([Select Id,Last_Contact_Date__c,Last_Meeting_Date__c From Account WHERE Id IN: acctIds]);
        
        map<Id,Note__c> nMap = new map<Id,Note__c>([Select Id,ActivityDate__c,Type__c,Status__c,Count_Towards_SLA__c From Note__c WHERE Id IN: noteIds]);
        
        Group_Member__c[] gmList = [Select Id,Client_Prospect__c,Last_Contact_Date__c,Last_Meeting_Date__c From Group_Member__c WHERE Client_Prospect__c IN: acctIds];
        
        for(Group_Member__c gm : gmList)
        {
            if(acctGmMap.containsKey(gm.Client_Prospect__c))
            {
                acctGmMap.get(gm.Client_Prospect__c).add(gm);
			}else
            {
                acctGmMap.put(gm.Client_Prospect__c,new Group_Member__c[]{gm});
            }
        }
        
        System.debug(gmList);
        
        System.debug(acctGmMap);
        System.debug(newMap.values());
        
        for(Note_Joiner__c n : newMap.values())
        {
            Note__c nTemp = nMap.get(n.Note__c);
            
            Group_Member__c[] gmTempSet = acctGmMap.get(n.Client_Prospect__c);
            Account aTemp = acctMap.get(n.Client_Prospect__c);
            
            if(aTemp != null && nTemp != null)
            {
                System.debug(aTemp);
                System.debug(nTemp);
                if(((aTemp.Last_Contact_Date__c < nTemp.ActivityDate__c) || aTemp.Last_Contact_Date__c == null)  && nTemp.Count_Towards_SLA__c)
                {
                    aTemp.Last_Contact_Date__c = nTemp.ActivityDate__c;                        
                }
                
                if(nTemp.Type__c == 'Meeting' && (((aTemp.Last_Meeting_Date__c < nTemp.ActivityDate__c) || aTemp.Last_Meeting_Date__c == null) && nTemp.Count_Towards_SLA__c))
                {
                    aTemp.Last_Meeting_Date__c = nTemp.ActivityDate__c;
				}
                setAccts.add(aTemp);
            }
            
            System.debug(gmTempSet);
            
            if(gmTempSet != null && !gmTempSet.isEmpty())
            {
                for(Group_Member__c gm : gmTempSet)
                {
                    System.debug(gm);
                    System.debug(nTemp);
                    if(gm != null && nTemp != null)
                    {
                        System.debug('Im In');
                        if(((gm.Last_Contact_Date__c < nTemp.ActivityDate__c) || gm.Last_Contact_Date__c == null)  && nTemp.Count_Towards_SLA__c)
                        {
                            gm.Last_Contact_Date__c = nTemp.ActivityDate__c;                        
                        }
                        
                        if(nTemp.Type__c == 'Meeting' && ((gm.Last_Meeting_Date__c < nTemp.ActivityDate__c) || gm.Last_Meeting_Date__c == null) && nTemp.Count_Towards_SLA__c)
                        {
                            gm.Last_Meeting_Date__c = nTemp.ActivityDate__c;
                        }
                        
                        setGms.add(gm);
                    }
                }
            }
        }

		System.debug(updAccts); 

        updGms.addAll(setGms);  
        updAccts.addAll(setAccts);     
        update updGms;
        update updAccts;
    }
}