HIL/src/objects/Group_Member__c.object
<CustomObject>
    <description>Custom object that acts as a junction between a Client &amp; Prospect record and a Relationship Group record.</description>
    <fields>
        <fullName>Client_Prospect__c</fullName>
        <label>Client/Prospect</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Relationship_Group__c</fullName>
        <label>Relationship Group</label>
        <referenceTo>Relationship_Group__c</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grandchild</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grandparent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Husband</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trustee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wife</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>GM-{00000}</displayFormat>
        <label>Group Member #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HIL/src/objects/Note__c.object
<CustomObject>
    <fields>
        <fullName>Account_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>SLANotes_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Private__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Private</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Relationship_Group__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep Code</label>
        <referenceTo>Rep_Code__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on someone else</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Note</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Do</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Note</label>
    <nameField>
        <displayFormat>Note-{YY}-{00000000}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL/src/objects/Note_Joiner__c.object
<CustomObject>
    <fields>
        <fullName>Client_Prospect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client &amp; Prospect</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Member</label>
        <referenceTo>Group_Member__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Note</label>
        <referenceTo>Note__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Relationship_Group__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>TEXT(Note__r.Type__c)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Note Joiner</label>
    <nameField>
        <displayFormat>N-{000000}</displayFormat>
        <label>Note Joiner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Note Joiners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HIL/src/objects/Relationship_Group__c.object
<CustomObject>
    <description>Custom object to track a combination of Client &amp; Prospect records related via many to many relationship with the Group Member junction object.</description>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep Code</label>
        <referenceTo>Rep_Code__c</referenceTo>
        <relationshipLabel>Relationship Groups</relationshipLabel>
        <relationshipName>Relationship_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holding Company</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Relationship Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL/src/objects/Rep_Code__c.object
<CustomObject>
    <description>Custom object to track all Rep Codes.</description>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <externalId>true</externalId>
        <label>Rep Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Rep Code</label>
    <nameField>
        <label>Rep Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rep Codes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL/src/objects/Rep_Code_User__c.object
<CustomObject>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep Code</label>
        <referenceTo>Rep_Code__c</referenceTo>
        <relationshipLabel>Rep Code Users</relationshipLabel>
        <relationshipName>Rep_Code_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Rep_Code_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rep Code User</label>
    <nameField>
        <label>Rep Code User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rep Code Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HIL/src/classes/SL_NoteExtension.cls
public with sharing class SL_NoteExtension
{

    //private final ApexPages.StandardController m_controller;
	//private Note__c m_note;
    public Note__c Note {get;set;}  
    public Note_Joiner__c UINoteJoiner {get;set;}
    private Set<Id> repcodeUserIDList;
    private  List<RelationshipGroupModel> RelatedRelationshipGroups {get;set;}
    public List<String> RelatedGroups {get;set;}
    
	public SL_NoteExtension()
    {
        Note = new Note__c();

        Note.OwnerId = UserInfo.getUserId();
        
        Note.Type__c = ApexPages.currentPage().getParameters().get('type');
        Note.Status__c = ApexPages.currentPage().getParameters().get('status');
        
        this.RelatedRelationshipGroups = new List<RelationshipGroupModel>();
        this.RelatedGroups = new  List<string>();
        
        Id lkupId = ApexPages.currentPage().getParameters().get('lkupId');
        
        if(lkupId != null)
        {
            Schema.SObjectType sObjType = lkupId.getSobjectType();
            
            if(sObjType == Schema.Account.SObjectType)
            {
                Note.Account_del__c = lkupId;
                populateRelatedGroups();
            }
            
            if(sObjType == Schema.Relationship_Group__c.SObjectType)
            {
                Note.Relationship_Group__c = lkupId;
                populateGroupMembers();
            }
        }
    }
    
    public List<Schema.FieldSetMember> getFields()
    {
        return SObjectType.Note__c.FieldSets.test.getFields();
    }
        
    
    public void populateGroupMembers()
    {
        Id relatedGroupId = Note.Relationship_Group__c;
        
        this.RelatedRelationshipGroups = new List<RelationshipGroupModel>();
        this.RelatedGroups = new  List<string>();
        
        /*Additional WHERE Filter, Rel_Group__r.Rep_Code__c IN: Set<RepCode_Ids>*/        
        List<Group_Member__c> groupMembers = [select Client_Prospect__r.Name,
                                                     Client_Prospect__c,
                                                     Relationship_Group__r.Rep_Code__c
                                                     From Group_Member__c
                                                     where Relationship_Group__c =: relatedGroupId];
		repcodeUserIDList = new Set<Id>();
        
        for (Group_Member__c member : groupMembers)
        {
            RelationshipGroupModel  model = new RelationshipGroupModel();
            
            repcodeUserIDList.add(member.Relationship_Group__r.Rep_Code__c);
            model.GroupName = member.Client_Prospect__r.Name;
            model.GroupID = member.Client_Prospect__c;
            
            this.RelatedGroups.add(member.Client_Prospect__c);
            this.RelatedRelationshipGroups.add(model);
        }
	}

	public void populateRelatedGroups()
    {
        Id relatedAccountId = Note.Account_del__c;
        
        this.RelatedRelationshipGroups = new List<RelationshipGroupModel>();
        this.RelatedGroups = new  List<string>();
        
        /*Query Rep_Code_User__c object to get Set<RepCode_Ids> current user belongs*/

        List<Rep_Code_User__c> repcodeUserList = [select Rep_Code__c from Rep_Code_User__c where User__c =: Note.OwnerId];
        repcodeUserIDList = new Set<Id>();
        
        for (Rep_Code_User__c reprecord: repcodeUserList)
        {
            repcodeUserIDList.add(reprecord.Rep_Code__c);
        }
        
        /*Additional WHERE Filter, Rel_Group__r.Rep_Code__c IN: Set<RepCode_Ids>*/        
        List<Group_Member__c> groupMembers = [select Relationship_Group__r.Name, Relationship_Group__c, Relationship_Group__r.Rep_Code__c from Group_Member__c where Client_Prospect__c =  :relatedAccountId  and  Relationship_Group__r.Rep_Code__c in :repcodeUserIDList];
		
        repcodeUserIDList.clear();
        
        for (Group_Member__c member : groupMembers)
        {
            RelationshipGroupModel  model = new RelationshipGroupModel();
            
            model.GroupName = member.Relationship_Group__r.Name;
            model.GroupID = member.Relationship_Group__c;
            
            this.RelatedGroups.add(member.Relationship_Group__c);
            this.RelatedRelationshipGroups.add(model);
            
            repcodeUserIDList.add(member.Relationship_Group__r.Rep_Code__c);
        }
	}
	
    public PageReference saveAndRedirect()
	{
    	if(Save())
        {
            if(Note.Account_del__c != null)
            {
                return new PageReference('/'+Note.Account_del__c);
            }
            
            if(Note.Relationship_Group__c != null)
            {
                return new PageReference('/'+Note.Relationship_Group__c);
            }
            
            return null;
    	}else 
    	{
        	return null;
    	}
	}
    
    public PageReference cancel()
    {
        if(Note.Account_del__c != null)
        {
            return new PageReference('/'+Note.Account_del__c);
        }
        
        if(Note.Relationship_Group__c != null)
        {
            return new PageReference('/'+Note.Relationship_Group__c);
        }
        
        return null;
    }

     public boolean Save()
     {
         boolean recordSaved = false;
         
         try
         {
            insert Note;

             Note_Joiner__c[] listNj = new Note_Joiner__c[]{};

             Note_Joiner__c firstNJ = new Note_Joiner__c();

             firstNJ.Client_Prospect__c = Note.Account_del__c;
             firstNJ.Relationship_Group__c = Note.Relationship_Group__c;
             firstNJ.Note__c = Note.Id;

             listNj.add(firstNJ);
                 
             for(String groupID : RelatedGroups)
             {
                 Note_Joiner__c oNotejoiner = new Note_Joiner__c();
                 oNotejoiner.Note__c = Note.Id;
                 
                 if(Note.Account_del__c != null)
                 {
                    oNotejoiner.Relationship_Group__c=groupID;
                 }
                 
                 if(Note.Relationship_Group__c != null)
                 {                    
                     oNotejoiner.Client_Prospect__c = groupId;
                 }
                 
                 listNj.add(oNotejoiner);
             }
             
             insert listNj;

             if(!Note.Private__c)
             {             
                 SL_Util_SharingController.RepCodeType[] shareList = new SL_Util_SharingController.RepCodeType[]{};
                     
                 for(Id i : repcodeUserIDList)
                 {
                     if(i != Note.OwnerId)
                     {
                     	shareList.add(new SL_Util_SharingController.RepCodeType(Note.Id,i));
                     }
                 }             
                 
                 insert SL_Util_SharingController.createSharingRecords(shareList, 'Edit');
             }
             
             recordSaved = true;
             
         }catch(DmlException ex)
         {
             ApexPages.addMessages(ex);
             recordSaved = false;
         }
         
         return recordSaved;
     }

	public void AccountPopulated()
 	{
    	populateRelatedGroups();
 	}
    
    public void GroupPopulated()
    {
        populateGroupMembers();
    }  

    public List<SelectOption> getRelatedRelationshipGroupsForView()
    {
        List<selectoption> options = new List<selectoption>();        

        for (RelationshipGroupModel a : RelatedRelationshipGroups) 
        {   
            options.add(new SelectOption(a.GroupID, a.GroupName));
        }             
                
        return options;          
    }

    public class RelationshipGroupModel
    {
        public RelationshipGroupModel(){}
        
        public boolean Include { get;set;}
        public String GroupName { get; set; }
        public String GroupID { get; set; }
    }
}