HIL/src/objects/Group_Member__c.object
<CustomObject>
    <description>Custom object that acts as a junction between a Client &amp; Prospect record and a Relationship Group record.</description>
    <fields>
        <fullName>Client_Prospect__c</fullName>
        <label>Client/Prospect</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Contact_Date__c</fullName>
        <label>Last Contact Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Meeting_Date__c</fullName>
        <label>Last Meeting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Relationship_Group__c</fullName>
        <label>Relationship Group</label>
        <referenceTo>Relationship_Group__c</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>GM-{00000}</displayFormat>
        <label>Group Member #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HIL/src/objects/Relationship_Group__c.object
<CustomObject>
    <description>Custom object to track a combination of Client &amp; Prospect records related via many to many relationship with the Group Member junction object.</description>
    <fields>
        <fullName>Last_Contact_Date__c</fullName>
        <label>Last Contact Date</label>
        <summarizedField>Group_Member__c.Last_Contact_Date__c</summarizedField>
        <summaryForeignKey>Group_Member__c.Relationship_Group__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Last_Meeting_Date__c</fullName>
        <label>Last Meeting Date</label>
        <summarizedField>Group_Member__c.Last_Meeting_Date__c</summarizedField>
        <summaryForeignKey>Group_Member__c.Relationship_Group__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep Code</label>
        <referenceTo>Rep_Code__c</referenceTo>
        <relationshipLabel>Relationship Groups</relationshipLabel>
        <relationshipName>Relationship_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL/src/objects/Rep_Code__c.object
<CustomObject>
    <description>Custom object to track all Rep Codes.</description>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <externalId>true</externalId>
        <label>Rep Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Rep Code</label>
    <nameField>
        <label>Rep Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rep Codes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL/src/objects/Rep_Code_User__c.object
<CustomObject>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep Code</label>
        <referenceTo>Rep_Code__c</referenceTo>
        <relationshipLabel>Rep Code Users</relationshipLabel>
        <relationshipName>Rep_Code_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Rep_Code_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rep Code User</label>
    <nameField>
        <label>Rep Code User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rep Code Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HIL FullSandbox/src/classes/SL_TestActivityHandlers_RM.cls
@isTest

private class SL_TestActivityHandlers_RM {
    
    private static Id idRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName = 'Person'].Id;

    static testMethod void SL_TestTaskHandler() {

        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        
        User objUser = new User(Alias = 'User111', Email='user1@user.com', 
                                EmailEncodingKey='UTF-8', LastName='Testing1', LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', ProfileId = p.Id, 
                                TimeZoneSidKey='America/Los_Angeles', UserName='user1kj1kj.212@user.com');
        insert objUser;
        
        Rep_Code__c objRepcode = new Rep_Code__c(Name = 'Test1', Rep_Code__c = '112');
        insert objRepcode;
        
        Rep_Code_User__c objRepUser = new Rep_Code_User__c(Name = 'Test', Rep_Code__c = objRepcode.Id, User__c = objUser.Id);
        insert objRepUser;
        
                
        // Create test relationship group record
        Relationship_Group__c rg = new Relationship_Group__c();
        rg.Name = 'Test RG';
        rg.Rep_Code__c = objRepcode.Id;
        insert rg;

        // Create test account record
        Account acct = new Account();
        acct.LastName = 'Test Account';
        acct.RecordTypeId = idRecordType;
        //acct.Primary_Relationship_Group__c = rg.Id;
        insert acct;

        Group_Member__c gm = new  Group_Member__c();
        gm.Client_Prospect__c = acct.Id;
        gm.Relationship_Group__c = rg.Id;
        insert gm;

        acct.Primary_Relationship_Group__c = rg.Id;
        update acct;

        // Retrieve test contact record
        Contact con = [SELECT Id FROM Contact WHERE AccountId = :acct.id LIMIT 1];

        // Create test task
        Task tsk = new Task();
        tsk.WhatId = acct.Id;
        tsk.WhoId = con.Id;
        tsk.ActivityDate = Date.today();
        tsk.Subject = 'Test Task';
        tsk.Status = 'Completed';
        tsk.OwnerId = objUser.Id;
        
        
        Task tsk1 = new Task();
        tsk1.WhatId = acct.Id;
        tsk1.WhoId = con.Id;
        tsk1.ActivityDate = Date.today();
        tsk1.Subject = 'Test Task';
        tsk1.Status = 'Completed';
        tsk1.OwnerId = objUser.Id;
        tsk1.Type = 'Other';
        
        
        List<Task> lstTask = new List<Task>();
        lstTask.add(tsk);
        lstTask.add(tsk1);

        insert lstTask;

        // Update test task as Type = Call
        tsk.Type = 'Call';
        SL_RecursionHelper.isUpdate = true;
        
        Test.startTest();
        update tsk;
        Test.stopTest();


        // Assertion for Account.Last_Contact_Date__c
        List<Account> acctList_LCD = new List<Account>();
        acctList_LCD = [SELECT Id, Last_Contact_Date__c FROM Account WHERE Id = :acct.id LIMIT 1];
        System.assertEquals(acctList_LCD[0].Last_Contact_Date__c, Date.today());

        // Assertion for Group_Member__c.Last_Contact_Date__c
        List<Group_Member__c> gmList_LCD = new List<Group_Member__c>();
        gmList_LCD = [SELECT Id, Last_Contact_Date__c FROM Group_Member__c WHERE Id = :gm.id LIMIT 1];
        //System.assertEquals(gmList_LCD[0].Last_Contact_Date__c, Date.today());


        // Update test task as Type = Meeting
        tsk.Type = 'Meeting';
        SL_RecursionHelper.isUpdate = true;
        update tsk;


        // Assertion for Account.Last_Meeting_Date__c
        List<Account> acctList_LMD = new List<Account>();
        acctList_LMD = [SELECT Id, Last_Meeting_Date__c FROM Account WHERE Id = :acct.id LIMIT 1];
        //System.assertEquals(acctList_LMD[0].Last_Meeting_Date__c, Date.today());

        // Assertion for Group_Member__c.Last_Meeting_Date__c
        List<Group_Member__c> gmList_LMD = new List<Group_Member__c>();
        gmList_LMD = [SELECT Id, Last_Meeting_Date__c FROM Group_Member__c WHERE Id = :gm.id LIMIT 1];
        //System.assertEquals(gmList_LMD[0].Last_Meeting_Date__c, Date.today());

    }

    static testMethod void SL_TestEventHandler() {

        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        
        User objUser = new User(Alias = 'User111', Email='user1@user.com', 
                                EmailEncodingKey='UTF-8', LastName='Testing1', LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', ProfileId = p.Id, 
                                TimeZoneSidKey='America/Los_Angeles', UserName='user1kj1kj.212@user.com');
        insert objUser;
        
        Rep_Code__c objRepcode = new Rep_Code__c(Name = 'Test1', Rep_Code__c = '112');
        insert objRepcode;
        
        Rep_Code_User__c objRepUser = new Rep_Code_User__c(Name = 'Test', Rep_Code__c = objRepcode.Id, User__c = objUser.Id);
        insert objRepUser;
        
        // Create test relationship group record
        Relationship_Group__c rg = new Relationship_Group__c();
        rg.Name = 'Test RG';
        rg.Rep_Code__c = objRepcode.Id;
        insert rg;

        // Create test account record
        Account acct = new Account();
        acct.LastName = 'Test Account';
        acct.RecordTypeId = idRecordType;
        //acct.Primary_Relationship_Group__c = rg.Id;
        insert acct;

        Group_Member__c gm = new Group_Member__c();
        gm.Client_Prospect__c = acct.Id;
        gm.Relationship_Group__c = rg.Id;

        insert gm;

        acct.Primary_Relationship_Group__c = rg.Id;
        update acct;

        // Retrieve test contact record
        Contact con = [SELECT Id FROM Contact WHERE AccountId = :acct.id LIMIT 1];

        // Create test event
        Event evt = new Event();
        evt.WhatId = acct.Id;
        evt.WhoId = con.Id;
        evt.StartDateTime = Datetime.now().addDays(-2);
        evt.EndDateTime = Datetime.now().addDays(-1);
        evt.Subject = 'Test Event';
        evt.OwnerId = objUser.id;
        insert evt;

        /** COMMENTED BLOCK
        
        // Update test event as Type = Call
        evt.Type = 'Call';
        SL_RecursionHelper.isUpdate = true;
        
        Test.startTest();
        update evt;
        Test.stopTest();

        // Assertion for Account.Last_Contact_Date__c
        List<Account> acctList_LCD = new List<Account>();
        acctList_LCD = [SELECT Id, Last_Contact_Date__c FROM Account WHERE Id = :acct.id LIMIT 1];
        System.assertEquals(acctList_LCD[0].Last_Contact_Date__c, Date.today().addDays(-1));

        // Assertion for Group_Member__c.Last_Contact_Date__c
        List<Group_Member__c> gmList_LCD = new List<Group_Member__c>();
        gmList_LCD = [SELECT Id, Last_Contact_Date__c FROM Group_Member__c WHERE Id = :gm.id LIMIT 1];
        System.assertEquals(gmList_LCD[0].Last_Contact_Date__c, Date.today().addDays(-1));
        
        **/

        // Update test event as Type = Meeting
        evt.Type = 'Meeting';
        SL_RecursionHelper.isUpdate = true;
        
        Test.startTest();
        update evt;
        Test.stopTest();


        // Assertion for Account.Last_Meeting_Date__c
        List<Account> acctList_LMD = new List<Account>();
        acctList_LMD = [SELECT Id, Last_Meeting_Date__c FROM Account WHERE Id = :acct.id LIMIT 1];
        // System.assert(acctList_LMD[0].Last_Meeting_Date__c != '');

        // Assertion for Group_Member__c.Last_Meeting_Date__c
        List<Group_Member__c> gmList_LMD = new List<Group_Member__c>();
        gmList_LMD = [SELECT Id, Last_Meeting_Date__c FROM Group_Member__c WHERE Id = :gm.id LIMIT 1];
        // System.assert(gmList_LMD[0].Last_Meeting_Date__c != '');

    }

}