HIL/src/objects/Group_Member__c.object
<CustomObject>
    <description>Custom object that acts as a junction between a Client &amp; Prospect record and a Relationship Group record.</description>
    <fields>
        <fullName>Client_Prospect__c</fullName>
        <label>Client/Prospect</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Contact_Date__c</fullName>
        <label>Last Contact Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Meeting_Date__c</fullName>
        <label>Last Meeting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Relationship_Group__c</fullName>
        <label>Relationship Group</label>
        <referenceTo>Relationship_Group__c</referenceTo>
        <relationshipLabel>Group Members</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grandchild</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grandparent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Husband</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trustee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wife</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>GM-{00000}</displayFormat>
        <label>Group Member #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HIL/src/objects/Note__c.object
<CustomObject>
    <fields>
        <fullName>Account_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>SLANotes_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ActivityDate__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Due Date Only</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Count_Towards_SLA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Count Towards SLA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Relationship_Group__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep Code</label>
        <referenceTo>Rep_Code__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Note</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Do</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Note</label>
    <nameField>
        <displayFormat>Note-{YY}-{00000000}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL/src/objects/Note_Joiner__c.object
<CustomObject>
    <fields>
        <fullName>Client_Prospect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client &amp; Prospect</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Member</label>
        <referenceTo>Group_Member__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Note</label>
        <referenceTo>Note__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Relationship_Group__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>TEXT(Note__r.Type__c)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Note Joiner</label>
    <nameField>
        <displayFormat>N-{000000}</displayFormat>
        <label>Note Joiner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Note Joiners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HIL/src/objects/Relationship_Group__c.object
<CustomObject>
    <description>Custom object to track a combination of Client &amp; Prospect records related via many to many relationship with the Group Member junction object.</description>
    <fields>
        <fullName>Last_Contact_Date__c</fullName>
        <label>Last Contact Date</label>
        <summarizedField>Group_Member__c.Last_Contact_Date__c</summarizedField>
        <summaryForeignKey>Group_Member__c.Relationship_Group__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Last_Meeting_Date__c</fullName>
        <label>Last Meeting Date</label>
        <summarizedField>Group_Member__c.Last_Meeting_Date__c</summarizedField>
        <summaryForeignKey>Group_Member__c.Relationship_Group__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep Code</label>
        <referenceTo>Rep_Code__c</referenceTo>
        <relationshipLabel>Relationship Groups</relationshipLabel>
        <relationshipName>Relationship_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holding Company</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Relationship Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL/src/objects/Rep_Code__c.object
<CustomObject>
    <description>Custom object to track all Rep Codes.</description>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <externalId>true</externalId>
        <label>Rep Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Rep Code</label>
    <nameField>
        <label>Rep Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rep Codes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL FullSandbox/src/classes/SL_NoteHandler.cls
/**
* \arg ClassName      : SL_NoteHandler
* \arg JIRATicket     : HIL-4
* \arg CreatedOn      : 13/FEB/2015
* \arg LastModifiedOn : 26/MAR/2015
* \arg CreatededBy    : Pankaj Ganwani
* \arg ModifiedBy     : Bryan Anderson
* \arg Description    : This class serves as handler for SL_Note and used to create sharing records corresponding to Note__c. This class calls SL_Util_SharingController for creating sharing records.
*/
public without sharing class SL_NoteHandler 
{
	static final String ACCESS_LEVEL = 'Read';
	
	/* Start - Constructor */
	public SL_NoteHandler()
	{
		//Do Nothing
	}
	/* End - Constructor */
	
	 /*
        * MethodName   : onAfterInsert
        * Param        : list of inserted Note__c records
        * Description  : This method is used to create sharing records corresponding to inserted Note__c records. This method calls createSharingRecords method for performing this operation.
    */
	public void onAfterInsert(Map<Id,Note__c> newMap)
	{
		SL_Note_Joiner_Handler njHandler = new SL_Note_Joiner_Handler(false,200);
		njHandler.createJoinerRecs(newMap);
		createSharingRecords(null,newMap);//calling method to create association of rep code ids with object record ids.
		
		//updateDatesOnClientAndHousehold(null, newMap.values());
	}

	public void onAfterUpdate(Map<Id,Note__c> oldMap, Map<Id,Note__c> newMap)
	{
		SL_Note_Joiner_Handler njHandler = new SL_Note_Joiner_Handler(false,200);
		njHandler.createJoinerRecs(newMap);
		
		myUpdateSLA(newMap.keySet(),false);
		
		//updateDatesOnClientAndHousehold(oldMap, newMap.values());
		//createSharingRecords(null,newMap);//calling method to create association of rep code ids with object record ids.
	}
	
	/******************Added by Lodhi 13 MAY 2015****************/
	
	public void onBeforeDelete(Map<Id, Note__c> mapIdToNoteOld)
	{
		myUpdateSLA(mapIdToNoteOld.keySet(),true);
	    
	    //updateDatesOnClientAndHousehold(null, mapIdToNoteOld.values());
	}
	
    /*
        * MethodName   : updateDatesOnClientAndHousehold
        * Param        : Map of Note__c
        * Description  : 
    */
    private void updateDatesOnClientAndHousehold(Map<Id, Note__c> mapIdToNoteOld, List<Note__c> lstNote)
    {
        Set<Id> setClientProspectId = new Set<Id>();
        Set<Id> setRelationGroupId = new Set<Id>();
        
        for(Note__c objNote : lstNote)
        {
            // if(mapIdToNoteOld == null || (objNote.Type__c != mapIdToNoteOld.get(objNote.Id).Type__c 
            //   || objNote.ActivityDate__c != mapIdToNoteOld.get(objNote.Id).ActivityDate__c))
            // {
                if(objNote.Account_del__c != null)
    	            setClientProspectId.add(objNote.Account_del__c);
    	        if(objNote.Relationship_Group__c != null)
    	            setRelationGroupId.add(objNote.Relationship_Group__c);   
            // }    	            
        }
        updateMembers(setClientProspectId, setRelationGroupId);
    }
    
    @future
    private static void updateMembers(Set<Id> setClientProspectId, Set<Id> setRelationGroupId)
    {
        Map<Id, Id> mapAccIdToMaxActivityDateNoteId = new Map<Id, Id>();
        Map<Id, Id> mapAccIdToNonMaxActivityDateNoteId = new Map<Id, Id>();
        Map<Id, Id> mapRelGrpIdToMaxActivityDateNoteId = new Map<Id, Id>();
        Map<Id, Id> mapRelGrpIdToNonMaxActivityDateNoteId = new Map<Id, Id>();
        Map<Id, Note__c> mapIdToNote = new Map<Id, Note__c>();
        List<Account> lstAccount = new List<Account>();
        List<Group_Member__c> lstGM = new List<Group_Member__c>();
        
        for(Note__c objNote : [SELECT Id, Account_del__c,
                                      Relationship_Group__c,
                                      ActivityDate__c
                                 FROM Note__c
                                WHERE Account_del__c IN : setClientProspectId 
                                  AND Count_Towards_SLA__c = true
                                  AND Type__c = 'Meeting'
                            ORDER BY ActivityDate__c DESC])
        {
            if(objNote.Account_del__c != null && !mapAccIdToMaxActivityDateNoteId.containsKey(objNote.Account_del__c))
                mapAccIdToMaxActivityDateNoteId.put(objNote.Account_del__c, objNote.Id);
        }  
        
        for(Note__c objNote : [SELECT Id, Account_del__c,
                                      Relationship_Group__c,
                                      ActivityDate__c
                                 FROM Note__c
                                WHERE Relationship_Group__c IN : setRelationGroupId
                                  AND Count_Towards_SLA__c = true
                                  AND Type__c = 'Meeting'
                            ORDER BY ActivityDate__c DESC])
        {
            if(objNote.Relationship_Group__c != null && !mapRelGrpIdToMaxActivityDateNoteId.containsKey(objNote.Relationship_Group__c))
                mapRelGrpIdToMaxActivityDateNoteId.put(objNote.Relationship_Group__c, objNote.Id);
        }      
        
        mapIdToNote = new Map<Id, Note__c>([SELECT Id, ActivityDate__c 
        									  FROM Note__c 
        									 WHERE Id IN : mapAccIdToMaxActivityDateNoteId.values()
        									    OR Id IN : mapRelGrpIdToMaxActivityDateNoteId.values()]);
        
        for(Note_Joiner__c objNoteJoiner : [SELECT Id, 
                                                   Note__c, 
                                                   Client_Prospect__c, 
                                                   Relationship_Group__c 
                                              FROM Note_Joiner__c
                                             WHERE Note__c IN : mapIdToNote.keySet()])
        {
        	if(objNoteJoiner.Client_Prospect__c != null) setClientProspectId.add(objNoteJoiner.Client_Prospect__c);
        	if(objNoteJoiner.Relationship_Group__c != null) setRelationGroupId.add(objNoteJoiner.Relationship_Group__c);
        }
        
        for(Id accountId :setClientProspectId )
        {
        	lstAccount.add(new Account(Id = accountId, 
        	                           Last_Meeting_Date__c = (mapAccIdToMaxActivityDateNoteId.containsKey(accountId))
        	                           						   ? mapIdToNote.get(mapAccIdToMaxActivityDateNoteId.get(accountId)).ActivityDate__c
        	                           						   : null));
        }
        if(!lstAccount.isEmpty())
            update lstAccount;
        
        for(Group_Member__c objGM : [SELECT Id, Client_Prospect__c, Relationship_Group__c FROM Group_Member__c 
        							  WHERE Client_Prospect__c IN : setClientProspectId OR Relationship_Group__c IN: setRelationGroupId])
    	{
    	    if(mapAccIdToMaxActivityDateNoteId.containsKey(objGM.Client_Prospect__c) && mapRelGrpIdToMaxActivityDateNoteId.containsKey(objGM.Relationship_Group__c))
    		{ 
    		    Date dtDate = (mapIdToNote.get(mapAccIdToMaxActivityDateNoteId.get(objGM.Client_Prospect__c)).ActivityDate__c > mapIdToNote.get(mapRelGrpIdToMaxActivityDateNoteId.get(objGM.Relationship_Group__c)).ActivityDate__c )
	                           ? mapIdToNote.get(mapAccIdToMaxActivityDateNoteId.get(objGM.Client_Prospect__c)).ActivityDate__c
	                           : mapIdToNote.get(mapRelGrpIdToMaxActivityDateNoteId.get(objGM.Relationship_Group__c)).ActivityDate__c;
    		    lstGM.add(new Group_Member__c(Id = objGM.Id, Last_Meeting_Date__c = dtDate));
    		}
    		
    		else if(mapAccIdToMaxActivityDateNoteId.containsKey(objGM.Client_Prospect__c) && !mapRelGrpIdToMaxActivityDateNoteId.containsKey(objGM.Relationship_Group__c))
    		{
    		    Date dtDate = mapIdToNote.get(mapAccIdToMaxActivityDateNoteId.get(objGM.Client_Prospect__c)).ActivityDate__c;   
    		    lstGM.add(new Group_Member__c(Id = objGM.Id, Last_Meeting_Date__c = dtDate));
    		}
    		
    		else if(!mapAccIdToMaxActivityDateNoteId.containsKey(objGM.Client_Prospect__c) && mapRelGrpIdToMaxActivityDateNoteId.containsKey(objGM.Relationship_Group__c))
    		{
    		    Date dtDate = mapIdToNote.get(mapRelGrpIdToMaxActivityDateNoteId.get(objGM.Relationship_Group__c)).ActivityDate__c;   
    		    lstGM.add(new Group_Member__c(Id = objGM.Id, Last_Meeting_Date__c = dtDate));
    		}
    		else
    		{
    		    lstGM.add(new Group_Member__c(Id = objGM.Id, Last_Meeting_Date__c = null));
    		}
    	} 
    	if(!lstGM.isEmpty())
    	    update lstGM;
    }
    
    
    /* End */
    	
	/******************Added by Lodhi 13 MAY 2015****************/
	
	/*
        * MethodName   : createSharingRecords
        * Param        : list of inserted Note__c records
        * Description  : This method is used to create sharing records corresponding to inserted Note__c records. This method calls createSharingRecords method of SL_Util_SharingController class.
    */
	
	
    public static void myUpdateSLA(Set<Id> nIds, Boolean isDelete)
    {
    	Set<Id> relGrpIds = new Set<Id>();
		Set<Id> acctIds = new Set<Id>();
		Set<Id> nIdsAcct = new Set<Id>();

		System.debug(nIds);

		map<Id,Account> acctMap = new map<Id,Account>();

		Note_Joiner__c[] njList = [Select Id,Note__c,Client_Prospect__c,Relationship_Group__c
								   From Note_Joiner__c
								   WHERE Note__c IN: nIds];

		for(Note_Joiner__c nj : njList)
		{
			if(nj.Client_Prospect__c != null)
			{
				acctIds.add(nj.Client_Prospect__c);
			}

			if(nj.Relationship_Group__c != null)
			{
				relGrpIds.add(nj.Relationship_Group__c);
			}
		}

		System.debug(acctIds);

		njList = [Select Id,Note__c
				  From Note_Joiner__c
				  WHERE Relationship_Group__c IN: relGrpIds];

		for(Note_Joiner__c nj : njList)
		{
			if(nj.Note__c != null)
			{
				nIdsAcct.add(nj.Note__c);
			}
		}

		System.debug(nIdsAcct);

		if(isDelete)
		{
			nIdsAcct.removeAll(nIds);
		}

		AggregateResult[] arNoteAcctContDate = [SELECT Client_Prospect__c client,MAX(Note__r.ActivityDate__c) maxDate
												 FROM Note_Joiner__c
												 WHERE Client_Prospect__c IN: acctIds AND Note__c IN: nIdsAcct AND Note__r.ActivityDate__c != null AND (Note__r.Type__c = 'Call' OR Note__r.Type__c = 'Note') AND Note__r.Count_Towards_SLA__c = true GROUP BY Client_Prospect__c];
		System.debug(arNoteAcctContDate);

		AggregateResult[] arNoteAcctMeetDate = [SELECT Client_Prospect__c client,MAX(Note__r.ActivityDate__c) maxDate
												 FROM Note_Joiner__c
												 WHERE Client_Prospect__c IN: acctIds AND Note__c IN: nIdsAcct AND Note__r.ActivityDate__c != null AND Note__r.Type__c = 'Meeting' AND Note__r.Count_Towards_SLA__c = true GROUP BY Client_Prospect__c];
		System.debug(arNoteAcctMeetDate);

		for(AggregateResult ar : arNoteAcctContDate)
		{
			Id acctId = (Id)ar.get('client');
			Date maxDate = (Date)ar.get('maxDate');
			
			if(acctMap.containsKey(acctId))
			{
				acctMap.get(acctId).Last_Contact_Date__c = maxDate;
			}else
			{
				acctMap.put(acctId, new Account(Id = acctId,Last_Contact_Date__c = maxDate));	
			}
		}

		for(AggregateResult ar : arNoteAcctMeetDate)
		{
			Id acctId = (Id)ar.get('client');
			Date maxDate = (Date)ar.get('maxDate');
			
			if(acctMap.containsKey(acctId))
			{
				acctMap.get(acctId).Last_Meeting_Date__c = maxDate;
			}else
			{
				acctMap.put(acctId, new Account(Id = acctId,Last_Meeting_Date__c = maxDate));	
			}
		}

		Group_Member__c[] gmList = [Select Id,Client_Prospect__c,Last_Contact_Date__c,Last_Meeting_Date__c
									From Group_Member__c
									WHERE Relationship_Group__c IN: relGrpIds];

		for(Group_Member__c gm : gmList)
		{
			if(acctMap != null && !acctMap.isEmpty() && acctMap.get(gm.Client_Prospect__c) != null)
			{
				Account a = acctMap.get(gm.Client_Prospect__c);
				gm.Last_Contact_Date__c = a.Last_Contact_Date__c;
				gm.Last_Meeting_Date__c = a.Last_Meeting_Date__c;
			}else
			{
				//gm.Last_Contact_Date__c = null;
				//gm.Last_Meeting_Date__c = null;
			}
		}


		System.debug(gmList);
		update gmList;
		System.debug(acctMap.values());
		update acctMap.values();
    }
	private void createSharingRecords(Map<Id,Note__c> oldMap, Map<Id,Note__c> newMap)
	{
		List<SL_Util_SharingController.RepCodeType> rcList = new List<SL_Util_SharingController.RepCodeType>();
		
		for(Note__c objNote : newMap.values())
		{
			if(objNote.Account_del__c != null && objNote.Rep_Code__c != null && objNote.Create_Sharing_Records__c)
			{
				rcList.add(new SL_Util_SharingController.RepCodeType(objNote.Id, objNote.Rep_Code__c));
			}
		}
		
		if(!rcList.isEmpty())
        {
			insert SL_Util_SharingController.createSharingRecords(rcList, ACCESS_LEVEL);
        }
	}
}