HIL/src/objects/Group_Member__c.object
<CustomObject>
    <description>Custom object that acts as a junction between a Client &amp; Prospect record and a Relationship Group record.</description>
    <fields>
        <fullName>Client_Prospect__c</fullName>
        <label>Client/Prospect</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Group_Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>GM-{00000}</displayFormat>
        <label>Group Member #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HIL/src/objects/Hilliard_Lyons_Account__c.object
<CustomObject>
    <description>Custom object to track the many to many relationship that exists between a Financial Account record and a Client &amp; Prospect record.</description>
    <fields>
        <fullName>Asset_Value_RU__c</fullName>
        <description>Field needed for Rollup</description>
        <label>Asset Value RU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Asset_Value__c</fullName>
        <formula>Financial_Account__r.Total_Account_Equity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Asset Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cash_Available_RU__c</fullName>
        <description>Field needed for Rollup</description>
        <label>Cash Available RU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cash_Available__c</fullName>
        <formula>Financial_Account__r.Cash_Available__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cash Available</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Hilliard Lyons Accounts</relationshipLabel>
        <relationshipName>Financial_Account_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Money_Market_RU__c</fullName>
        <description>Field needed for Rollup</description>
        <label>Money Market RU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Money_Market__c</fullName>
        <formula>Financial_Account__r.Money_Market_Balance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Money Market</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Revenue_Value_RU__c</fullName>
        <description>Field needed for Rollup</description>
        <label>Revenue Value_RU</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Revenue_Value__c</fullName>
        <formula>Financial_Account__r.Revenue__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Revenue Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Hilliard Lyons Account</label>
    <nameField>
        <displayFormat>HLA-{00000}</displayFormat>
        <label>Hilliard Lyons Account#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hilliard Lyons Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HIL/src/classes/SL_HilliardLyonsAccountHandler.cls
/**
* \arg ClassName      : SL_HilliardLyonsAccountHandler
* \arg JIRATicket     : HIL-7
* \arg CreatedOn      : 20/FEB/2015
* \arg LastModifiedOn : -
* \arg CreatededBy    : Pankaj Ganwani
* \arg ModifiedBy     : -
* \arg Description    : This class serves as handler class for SL_HilliardLyonsAccount trigger and is used to update the HL account records to copy the cross object formula field values to corresponding place holder fields.
*/
public with sharing class SL_HilliardLyonsAccountHandler 
{
	/* Start - Variables */
	/* End - Variables */
	
	/* Start - Constuctor */
	public SL_HilliardLyonsAccountHandler()
	{
		//Do Nothing
	}
	/* End - Constuctor */
	
	/*
        * MethodName   : onBeforeInsert
        * Param        : new and old map of financial account records
        * Description  : This method is used to update the Hilliard Lyons Account records corresponding to financial accounts, which in turn updates the group member records
    */
	public void onBeforeInsert(List<Hilliard_Lyons_Account__c> lstHLAccount)
	{
		updateHLAccounts(lstHLAccount);
	}
	
	/*
        * MethodName   : onAfterInsert
        * Param        : new and old map of financial account records
        * Description  : This method is used to update the Hilliard Lyons Account records corresponding to financial accounts, which in turn updates the group member records
    */
	public void onAfterInsert(List<Hilliard_Lyons_Account__c> lstHLAccount)
	{
		updateGroupMemberRecords(lstHLAccount);
	}
	
	/*
        * MethodName   : onAfterUpdate
        * Param        : new and old map of financial account records
        * Description  : This method is used to update the Hilliard Lyons Account records corresponding to financial accounts, which in turn updates the group member records
    */
	public void onAfterUpdate(Map<Id,Hilliard_Lyons_Account__c> newMap, Map<Id,Hilliard_Lyons_Account__c> oldMap)
	{
		Set<String> setChkFields = new Set<String>{'Role__c'};// set to contain the fields we need to check for
		Map<Id, Sobject> mapIdToHLAccount = new Map<Id, Sobject>();// map to updated hl account records
		mapIdToHLAccount = SL_DiffRecordUtil.getRecordsWithDiff(oldMap, newMap, setChkFields);//calling util class method to compare the values of old map and new map.
		
		if(!mapIdToHLAccount.isEmpty())
		{
			updateGroupMemberRecords(mapIdToHLAccount.values());
		}
	}
	
	/*
        * MethodName   : onAfterDelete
        * Param        : new and old map of financial account records
        * Description  : This method is used to update the Hilliard Lyons Account records corresponding to financial accounts, which in turn updates the group member records
    */
	public void onAfterDelete(List<Hilliard_Lyons_Account__c> lstHLAccount)
	{
		updateGroupMemberRecords(lstHLAccount);
	}
	
	/*
        * MethodName   : onAfterUndelete
        * Param        : new and old map of financial account records
        * Description  : This method is used to update the Hilliard Lyons Account records corresponding to financial accounts, which in turn updates the group member records
    */
	public void onAfterUndelete(List<Hilliard_Lyons_Account__c> lstHLAccount)
	{
		updateGroupMemberRecords(lstHLAccount);
	}
	
	/*
        * MethodName   : updateHLAccounts
        * Param        : new and old map of financial account records
        * Description  : This method is used to update the Hilliard Lyons Account records corresponding to financial accounts, which in turn updates the group member records
    */
	private void updateHLAccounts(List<Hilliard_Lyons_Account__c> lstHLAccountToUpdate)
	{
		//Iterating over hl accounts to copy the values of formula fields to repective place holder fields.
		for(Hilliard_Lyons_Account__c objHLAccount : lstHLAccountToUpdate)
		{
			objHLAccount.Asset_Value_RU__c = objHLAccount.Asset_Value__c;
			objHLAccount.Cash_Available_RU__c = objHLAccount.Cash_Available__c;
			objHLAccount.Money_Market_RU__c = objHLAccount.Money_Market__c;
			objHLAccount.Revenue_Value_RU__c = objHLAccount.Revenue_Value__c;
		}			
	}
	
	/*
        * MethodName   : updateGroupMemberRecords
        * Param        : new and old map of financial account records
        * Description  : This method is used to update the Hilliard Lyons Account records corresponding to financial accounts, which in turn updates the group member records
    */
	private void updateGroupMemberRecords(List<Hilliard_Lyons_Account__c> lstHLAccount)
	{
		Set<Id> setClientIds = new Set<Id>();// this set is used to contain the ids of Client(Account) records.
		
		for(Hilliard_Lyons_Account__c objHLAccount : lstHLAccount)
		{
			setClientIds.add(objHLAccount.Client__c);
		}
		if(!setClientIds.isEmpty())
		{
			SL_UpdateGroupMemberController.updateGroupMembers(new Map<Id, Group_Member__c>([SELECT Id FROM Group_Member__c WHERE Client_Prospect__c IN : setClientIds]).keyset());
		}
	}
}