HIL/src/objects/Note__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on someone else</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject_Text__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Note</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Do</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Note</label>
    <nameField>
        <displayFormat>Note-{YY}-{00000000}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL FullSandbox/src/classes/SL_HomePageOpenActivitiesController.cls
/**
*  ClassName      : SL_HomePageOpenActivitiesController 
*  JIRATicket     : HIL-33
*  CreatedOn      : 24/SEP/2015
*  ModifiedBy     : Sanath
*  Description    : This class serves as controller for Home page VF page namely SL_HomePageOpenActivities 
*/

public class SL_HomePageOpenActivitiesController 
{
    /* Start - Variables */
    public List<Note__c> lstOpenNotes              {get;set;}
    public Boolean renderPageBlock                 {get;set;}
    /* End - Variables */
    
    /* Start - Constructor */ 
    public SL_HomePageOpenActivitiesController()
    {
        lstOpenNotes = new List<Note__c>();
        fetchOpenActivities();
    }
    /* End - Constructor */
    
     /*
        * MethodName        : fetchOpenActivities
        * param             : -
        * Description       : This function fetches all the open activities related to the current logged in user in descending order with LIMIT 5
    */
      
    private void fetchOpenActivities()
    { 
        for(Note__c objNote : [Select   Id, 
                                        Type__c,
                                        Status__c,
                                        CreatedDate,
                                        OwnerId, 
                                        Subject_Text__c
                               FROM Note__c 
                               WHERE Status__c='Open' 
                               AND Type__c='Task'
                               AND OwnerId =: userinfo.getuserid()
                               ORDER BY CreatedDate DESC LIMIT 5])
        {
            lstOpenNotes.add(objNote);
        }
        
        if(!lstOpenNotes.isEmpty())
            renderPageBlock = true;
        else
           {    
               renderPageBlock = false;
               Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'No Open Activities to Display'));
           }
    }
}