HIL/src/objects/Note__c.object
<CustomObject>
    <fields>
        <fullName>Account_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>SLANotes_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ActivityDate__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Due Date Only</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CallDisposition__c</fullName>
        <label>Call Result</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CallObject__c</fullName>
        <label>Call Object Identifier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CallType__c</fullName>
        <label>Call Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Count_Towards_SLA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Count Towards SLA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Create_Joiner_Records__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Joiner Records</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Import_ID__c</fullName>
        <externalId>true</externalId>
        <label>Import ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Import_Text__c</fullName>
        <label>Import Text</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Normal</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RecurrenceEndDateOnly__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurrenceInstance__c</fullName>
        <label>Recurrence Instance</label>
        <picklist>
            <picklistValues>
                <fullName>First</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fourth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RecurrenceMonthOfYear__c</fullName>
        <label>Recurrence Month of Year</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RecurrenceStartDateOnly__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurrenceTimeZoneSidKey__c</fullName>
        <label>Recurrence Time Zone</label>
        <picklist>
            <picklistValues>
                <fullName>Pacific/Kiritimati</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pacific/Chatham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pacific/Auckland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pacific/Enderbury</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pacific/Tongatapu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Kamchatka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pacific/Fiji</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pacific/Norfolk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia/Lord_Howe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia/Sydney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pacific/Guadalcanal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia/Adelaide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia/Brisbane</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia/Darwin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Seoul</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Tokyo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Hong_Kong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Kuala_Lumpur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Manila</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Shanghai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Singapore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Taipei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia/Perth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Bangkok</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Ho_Chi_Minh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Jakarta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Rangoon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Dhaka</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Kathmandu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Colombo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RecurrenceType__c</fullName>
        <label>Recurrence Type</label>
        <picklist>
            <picklistValues>
                <fullName>RecursDaily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RecursEveryWeekday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RecursMonthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RecursMonthlyNth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RecursWeekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RecursYearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RecursYearlyNth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Relationship_Group__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReminderDateTime__c</fullName>
        <label>Reminder Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on someone else</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject_Text__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <picklist>
            <picklistValues>
                <fullName>Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Note</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Do</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Note</label>
    <nameField>
        <displayFormat>Note-{YY}-{00000000}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL/src/objects/Relationship_Group__c.object
<CustomObject>
    <description>Custom object to track a combination of Client &amp; Prospect records related via many to many relationship with the Group Member junction object.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holding Company</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Relationship Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL FullSandbox/src/classes/SL_Batch_ConvertActivities.cls
global class SL_Batch_ConvertActivities implements Database.Batchable<sObject>
{	
	String query;
	Datetime lastRunDate;
	
	global SL_Batch_ConvertActivities()
	{
		lastRunDate = System.now().addMinutes(-15);

		query = 'Select Id,WhatId,WhoId,CallDisposition,CallObject,CallType,'+
               	'Description,ActivityDate,Count_Towards_SLA__c,'+
               	'Priority,Status,Subject,Type,RecurrenceInstance,'+
               	'RecurrenceMonthOfYear,RecurrenceTimeZoneSidKey,'+
               	'RecurrenceType,OwnerId,ReminderDateTime,'+
               	'RecurrenceEndDateOnly,RecurrenceStartDateOnly,'+
               	'Import_ID__c,Import_Text__c,(Select Id From Attachments) '+
               	'From Task '+
               	'WHERE CreatedDate >:lastRunDate';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC)
	{
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope)
   	{
   		Task[] tempList = (Task[])scope;

   		List<Note__c> lstNote = new List<Note__c>();// list to hold the note records that need to be inserted.
      map<Id,Id> acctContMap = new map<Id,Id>();
      Set<Id> cIds = new Set<Id>();
      map<Id,Set<Id>> taskAttMap = new map<Id,Set<Id>>();
      Attachment[] attListMstr = new Attachment[]{};

      for(Task t : tempList)
      {
        if(t.WhoId != null)
        {
          cIds.add(t.WhoId);
        }

        if(!t.Attachments.isEmpty())
        {
          Set<Id> attIds = new Set<Id>();

          for(Attachment a : t.Attachments)
          {
            attIds.add(a.Id);
          }

          taskAttMap.put(t.Id,attIds);
        }
      }

      Account[] aList = [Select Id,PersonContactId From Account WHERE PersonContactId IN: cIds];

      for(Account a : aList)
      {
        acctContMap.put(a.PersonContactId,a.Id);
      }

        for(Task objTask : tempList)
        {
            if(objTask.Type!='To Do')
            {
                Id acctId;
                Id relGrpId;

                if(objTask.WhatId!=null)
                {
                  if(objTask.WhatId.getSobjectType() == Account.getSobjectType())
                  {
                    acctId = objTask.WhatId;
                  }else if(objTask.WhatId.getSobjectType() == Relationship_Group__c.getSobjectType())
                  {
                    relGrpId = objTask.WhatId;
                  }
                }

                if(objTask.WhatId == null && objTask.WhoId != null)
                {
                  acctId = acctContMap.get(objTask.WhoId);
                }

                lstNote.add(new Note__c(Account_Del__c = acctId,
                                        CallObject__c = objTask.CallObject, CallDisposition__c = objTask.CallDisposition,
                                        Relationship_Group__c = relGrpId,
                                        CallType__c = objTask.CallType, Description__c = objTask.Description, ActivityDate__c = objTask.ActivityDate,
                                        Count_Towards_SLA__c = objTask.Count_Towards_SLA__c, Import_ID__c = objTask.Id, Import_Text__c = objTask.Import_Text__c,
                                        Priority__c = objTask.Priority, Status__c = objTask.Status, Subject__c = objTask.Subject, Subject_Text__c = objTask.Subject,
                                        Type__c = objTask.Type, RecurrenceInstance__c = objTask.RecurrenceInstance, RecurrenceMonthOfYear__c = objTask.RecurrenceMonthOfYear,
                                        RecurrenceTimeZoneSidKey__c = objTask.RecurrenceTimeZoneSidKey, RecurrenceType__c = objTask.RecurrenceType, OwnerId = objTask.OwnerId,
                                        ReminderDateTime__c = objTask.ReminderDateTime, RecurrenceEndDateOnly__c = objTask.RecurrenceEndDateOnly, RecurrenceStartDateOnly__c = objTask.RecurrenceStartDateOnly,
                                        Create_Joiner_Records__c = true));
            }
        }

        insert lstNote;

        for(Note__c n : lstNote)
        {
          if(taskAttMap.containsKey(n.Import_ID__c))
          {
            Attachment[] attList = [Select Id,Name,Body
                                    From Attachment
                                    WHERE Id IN: taskAttMap.get(n.Import_ID__c)];

            for(Attachment a : attList)
            {
              a.Id = null;
              a.ParentId = n.Id;
            }

            attListMstr.addAll(attList);
          }
        }

        Task[] delList = new Task[]{};

        for(Task t : tempList)
        {
          if(t.Type != 'To Do')
          {
            delList.add(t);
          }
        }

        insert attListMstr;

        delete delList;
	}
	
	global void finish(Database.BatchableContext BC)
	{
		
	}
	
}