HIL/src/objects/Note__c.object
<CustomObject>
    <fields>
        <fullName>Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Relationship_Group__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Note</label>
    <nameField>
        <displayFormat>Note-{YY}-{00000000}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL/src/objects/Note_Joiner__c.object
<CustomObject>
    <fields>
        <fullName>Client_Prospect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client &amp; Prospect</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Note</label>
        <referenceTo>Note__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Relationship_Group__c</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Note Joiner</label>
    <nameField>
        <displayFormat>N-{000000}</displayFormat>
        <label>Note Joiner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Note Joiners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HIL/src/objects/Relationship_Group__c.object
<CustomObject>
    <description>Custom object to track a combination of Client &amp; Prospect records related via many to many relationship with the Group Member junction object.</description>
    <label>Relationship Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL FullSandbox/src/classes/SL_Ctrl_DeleteNote.cls
public with sharing class SL_Ctrl_DeleteNote
{
    public String parId;
    public Note_Joiner__c nj;

    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public SL_Ctrl_DeleteNote(ApexPages.StandardController stdController)
    {
        nj = [Select Id,Note__c,Client_Prospect__c,Relationship_Group__c
                             From Note_Joiner__c WHERE Id =: stdController.getId()];
        parId = '';

        if(nj.Client_Prospect__c != null)
        {
            parId = nj.Client_Prospect__c;
        }

        if(nj.Relationship_Group__c != null)
        {
            parId = nj.Relationship_Group__c;
        }
    }

    public PageReference goToParent()
    {
        delete new Note__c(Id=nj.Note__c);
        return new PageReference('/'+parId);
    }
}