HIL/src/objects/Relationship_Group__c.object
<CustomObject>
    <description>Custom object to track a combination of Client &amp; Prospect records related via many to many relationship with the Group Member junction object.</description>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep Code</label>
        <referenceTo>Rep_Code__c</referenceTo>
        <relationshipLabel>Relationship Groups</relationshipLabel>
        <relationshipName>Relationship_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL/src/objects/Rep_Code__c.object
<CustomObject>
    <description>Custom object to track all Rep Codes.</description>
    <fields>
        <fullName>Rep_Code__c</fullName>
        <externalId>true</externalId>
        <label>Rep Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Rep Code</label>
    <nameField>
        <label>Rep Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rep Codes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

HIL FullSandbox/src/classes/SL_Relationship_GroupHelper.cls
/**  
* \arg ClassName        : SL_Relationship_GroupHelper
* \arg JIRATicket       : 
* \arg CreatedOn        : 
* \arg LastModifiedOn   : 
* \arg CreatededBy      : 
* \arg ModifiedBy       : 
* \arg Description      : Helper class
*/
public with sharing class SL_Relationship_GroupHelper {

/*BEGIN PROPERTIES*/

/*END PROPERTIES*/

/***************************************************
*	SHARED METHODS    					   		   *
***************************************************/

/***************************************************
*	BEFORE INSERT METHODS    					   *
***************************************************/

/***************************************************
*	BEFORE UPDATE METHODS    					   *
***************************************************/

/***************************************************
*	BEFORE DELETE METHODS    					   *
***************************************************/

/***************************************************
*	AFTER INSERT METHODS    					   *
***************************************************/

public static void updateSharing(map<Id,Relationship_Group__c> newMap)
{
	Relationship_Group__Share[] relSharing = new Relationship_Group__Share[]{};

	relSharing = [Select Id
				  From Relationship_Group__Share
				  WHERE ParentId IN: newMap.keyset() AND RowCause = 'Manual'];

	delete relSharing;

	SL_Util_SharingController.RepCodeType[] shareList = new SL_Util_SharingController.RepCodeType[] {};

    if(newMap != null && !newMap.isEmpty())
    {
        for(Id i : newMap.keySet())
        {
            shareList.add(new SL_Util_SharingController.RepCodeType(i, newMap.get(i).Rep_Code__c));
        }
    }

    Database.insert(SL_Util_SharingController.createSharingRecords(shareList, 'Edit'),false);
}

/***************************************************
*	AFTER UPDATE METHODS    					   *
***************************************************/

/***************************************************
*	AFTER DELETE METHODS    					   *
***************************************************/

/***************************************************
*	AFTER UNDELETE METHODS    					   *
***************************************************/

}